#+title: dogen.openapi
#+options: <:nil c:nil todo:nil ^:nil d:nil date:nil author:nil
* document
** openapi
:dogen-properties:
:type: std::string
:end:

The semantic version number of the OpenAPI Specification version that the OpenAPI document uses.

** info
:dogen-properties:
:type: info
:end:

Provides metadata about the API.

** servers
:dogen-properties:
:type: std::list<server>
:end:

An array of Server Objects, which provide connectivity information to a target server.

** paths
:dogen-properties:
:type: paths
:end:

The available paths and operations for the API.

** components
:dogen-properties:
:type: components
:end:

An element to hold various schemas for the specification.

** security
:dogen-properties:
:type: security_requirements
:end:

A declaration of which security mechanisms can be used across the API.

** tags
:dogen-properties:
:type: tags
:end:

A list of tags used by the specification with additional metadata.

** external_docs
:dogen-properties:
:type: external_documentation
:end:

Additional external documentation.

* info
** title
:dogen-properties:
:type: std::string
:end:

The title of the application.

** description
:dogen-properties:
:type: std::string
:end:

A short description of the application. CommonMark syntax may be used for rich text representation.

** terms_of_service
:dogen-properties:
:type: std::string
:end:

A URL to the Terms of Service for the API.

** contact
:dogen-properties:
:type: contact
:end:

The contact information for the exposed API.

** license
:dogen-properties:
:type: license
:end:

The license information for the exposed API.

** version
:dogen-properties:
:type: std::string
:end:

The version of the OpenAPI document itself.

* server
** url
:dogen-properties:
:type: std::string
:end:

A URL to the target host.

** description
:dogen-properties:
:type: std::string
:end:

An optional string describing the host designated by the URL.

** variables
:dogen-properties:
:type: std::unordered_map<std::string, server_variable>
:end:

A map between a variable name and its value. The value is used for substitution in the server's URL template.

* paths
* components
** schemas
:dogen-properties:
:type: std::unordered_map<std::string, schema>
:end:

An object to hold reusable schema objects.

** responses
:dogen-properties:
:type: std::unordered_map<std::string, response>
:end:

An object to hold reusable response objects.

** parameters
:dogen-properties:
:type: std::unordered_map<std::string, parameter>
:end:

An object to hold reusable parameter objects.

** examples
:dogen-properties:
:type: std::unordered_map<std::string, example>
:end:

An object to hold reusable examples objects.

** request_bodies
:dogen-properties:
:type: std::unordered_map<std::string, request_body>
:end:

An object to hold reusable request bodies objects.

** headers
:dogen-properties:
:type: std::unordered_map<std::string, request_header>
:end:

An object to hold reusable header objects.

** security_schemes
:dogen-properties:
:type: std::unordered_map<std::string, security_scheme>
:end:

An object to hold reusable security scheme objects.

** links
:dogen-properties:
:type: std::unordered_map<std::string, link>
:end:

An object to hold reusable links objects.

** callbacks
:dogen-properties:
:type: std::unordered_map<std::string, callback>
:end:

An object to hold reusable callbacks objects.

* security_requirements
* tags
* externalDocs
* external_documentation
* contact
** name
:dogen-properties:
:type: std::string
:end:

The identifying name of the contact person/organization.

** url
:dogen-properties:
:type: std::string
:end:

The URL pointing to the contact information.

** email
:dogen-properties:
:type: std::string
:end:

The email address of the contact person/organization.

* licence
** name
:dogen-properties:
:type: std::string
:end:

The license name used for the API.

** url
:dogen-properties:
:type: std::string
:end:

A URL to the license used for the API.

* server_variable
** enumeration
:dogen-properties:
:type: std::list<std::string>
:end:

An enumeration of string values to be used if the substitution options are from a limited set.

** default_value
:dogen-properties:
:type: std::string
:end:

The default value to use for substitution.

** description
:dogen-properties:
:type: std::string
:end:

An optional description for the server variable.

* schema
