@startuml
set namespaceSeparator ::
namespace tracing #F2F2F2 {
        class run_event <<masd::orm::object, Timestamped>> #CCFFE6 {
                +{field} run_event_key run_event_key
                +{field} version std::string
                +{field} payload json
                +{field} activity std::string
                +{field} logging_impact std::string
                +{field} tracing_impact std::string
}

        class run_id <<masd::orm::value, masd::primitive>> #B3FFD9 {
}

        class json <<masd::orm::value, masd::primitive>> #B3FFD9 {
}

        class transform_id <<masd::orm::value, masd::primitive>> #B3FFD9 {
}

        class Timestamped <<masd::object_template>> #E3B6F6 {
                +{field} timestamp boost::posix_time::ptime
}

        class transform_event <<masd::orm::object, Timestamped>> #CCFFE6 {
                +{field} transform_event_key transform_event_key
                +{field} run_id run_id
                +{field} transform_type transform_type
                +{field} transform_id transform_id
                +{field} payload json
                +{field} model_id std::string
                +{field} parent_transform transform_instance_id
}

        class JsonContent <<masd::object_template>> #E3B6F6 {
                +{field} json_content json
}

        class log_event <<masd::orm::object, Timestamped>> #CCFFE6 {
                +{field} run_id run_id
                +{field} component std::string
                +{field} severity std::string
                +{field} message std::string
}

        enum transform_type <<masd::enumeration>> #F2DAFD {
                +{field} chain
                +{field} leaf
}

        class relational_backend <<dogen::handcrafted::typeable, dogen::pretty_printable>> #FFFACD {
}

        class relational_backend_factory <<dogen::handcrafted::typeable>> #FFFACD {
}

        class transform_instance_id <<masd::orm::value, masd::primitive>> #B3FFD9 {
}

        enum event_type <<masd::enumeration>> #F2DAFD {
                +{field} start
                +{field} end
}

        class run_event_key <<masd::orm::value>> #B3FFD9 {
                +{field} run_id run_id
                +{field} event_type event_type
}

        class transform_event_key <<masd::orm::value>> #B3FFD9 {
                +{field} transform_instance_id transform_instance_id
                +{field} event_type event_type
}

        class log_backend <<dogen::handcrafted::typeable>> #FFFACD {
}

}

class initializer <<dogen::handcrafted::typeable>> #FFFACD {
}

class main <<masd::entry_point, dogen::untypable>> #DDA9F3 {
}

class common <<masd::orm::common_odb_options>> #80FFBF {
}

class CMakeLists <<masd::build::cmakelists>> #99CB99 {
}

@enduml
