#+CAPTION: Project Licence
#+ATTR_HTML: :align center
[[https://raw.githubusercontent.com/DomainDrivenConsulting/dogen/master/LICENCE]][[https://img.shields.io/badge/license-GPL_3-green.svg?dummy]]

* Overview

*Dogen* is a code generator designed to target domain models, inspired
by the [[http://en.wikipedia.org/wiki/Domain-driven_design][domain driven design]] methodology. Our main objective is to
automate the modeling process as much as possible: the user creates
domain models using a supported UML tool and respecting a set of
predefined restrictions; Dogen then uses the tool's diagram files to
generate the source code representation. The generated code contains
most of the services required from a typical C++ domain object such as
serialisation, hashing, streaming and so on.

Please note that *the code generated by Dogen is C++-11 only.*

* Useful Links

- Git repository: [[https://github.com/DomainDrivenConsulting/dogen][github]], [[https://bitbucket.org/marco_craveiro/dogen/overview][bitbucket]]
- [[http://my.cdash.org/index.php?project=Dogen][Continuous Integration]]
- [[https://github.com/kitanda/dogen/blob/master/doc/manual/manual.org][Manual]]
- [[https://github.com/kitanda/dogen/tree/master/doc/agile][Sprint logs]]
- [[https://www.youtube.com/watch?v=Z7k8qbImXkU][Demo (a few sprints old)]]

* Obtaining Dogen

Please see section [[https://github.com/DomainDrivenConsulting/dogen/blob/master/doc/manual/manual.org#obtaining-dogen][Obtaining Dogen]] for instructions on how to install
binary packages or compile from source.

* Feedback

If you have problems using Dogen or suggestions on how to improve it,
please use the [[https://github.com/kitanda/dogen/issues][github issues]]. If you are submitting a bug, please see
the instructions [[https://github.com/DomainDrivenConsulting/dogen/blob/master/doc/manual/manual.org#submitting-bug-reports][in the manual]] on what information to provide.

If you would like to submit a patch for inclusion, please fork us on
github and submit a pull request. If you are unable to do so, please
create an issue and append the patch to it.
