/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * These files are code-generated via overrides to test dogen. Do not commit them.
 *
 * Generation timestamp: 2022-10-20T10:20:30
 * WARNING: do not edit this file manually.
 * Generated by MASD Dogen v1.0.33
 *
 * Copyright (C) 2012-2015 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 */
#include "dogen.identification/test_data/entities/logical_id_td.hpp"
#include "dogen.logical/test_data/entities/structural/module_td.hpp"
#include "dogen.logical/test_data/entities/structural/object_td.hpp"
#include "dogen.logical/test_data/entities/structural/builtin_td.hpp"
#include "dogen.logical/test_data/entities/structural/visitor_td.hpp"
#include "dogen.logical/test_data/entities/structural/assistant_td.hpp"
#include "dogen.logical/test_data/entities/structural/exception_td.hpp"
#include "dogen.logical/test_data/entities/structural/primitive_td.hpp"
#include "dogen.logical/test_data/entities/structural/entry_point_td.hpp"
#include "dogen.logical/test_data/entities/structural/enumeration_td.hpp"
#include "dogen.logical/test_data/entities/structural/object_template_td.hpp"
#include "dogen.logical/test_data/entities/structural/element_repository_td.hpp"

namespace {

dogen::identification::entities::logical_id
create_dogen_identification_entities_logical_id(const unsigned int position) {
    return dogen::identification::entities::logical_id_generator::create(position);
}

dogen::logical::entities::structural::module*
create_dogen_logical_entities_structural_module_ptr(const unsigned int position) {
    return dogen::logical::entities::structural::module_generator::create_ptr(position);
}

boost::shared_ptr<dogen::logical::entities::structural::module>
create_boost_shared_ptr_dogen_logical_entities_structural_module(unsigned int position) {
    boost::shared_ptr<dogen::logical::entities::structural::module> r(
        create_dogen_logical_entities_structural_module_ptr(position));
    return r;
}

std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::module> > create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_module(unsigned int position) {
    std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::module> > r;
    for (unsigned int i(0); i < 4; ++i) {
        r.insert(std::make_pair(create_dogen_identification_entities_logical_id(position + i), create_boost_shared_ptr_dogen_logical_entities_structural_module(position + i)));
    }
    return r;
}

dogen::logical::entities::structural::object_template*
create_dogen_logical_entities_structural_object_template_ptr(const unsigned int position) {
    return dogen::logical::entities::structural::object_template_generator::create_ptr(position);
}

boost::shared_ptr<dogen::logical::entities::structural::object_template>
create_boost_shared_ptr_dogen_logical_entities_structural_object_template(unsigned int position) {
    boost::shared_ptr<dogen::logical::entities::structural::object_template> r(
        create_dogen_logical_entities_structural_object_template_ptr(position));
    return r;
}

std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::object_template> > create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_object_template(unsigned int position) {
    std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::object_template> > r;
    for (unsigned int i(0); i < 4; ++i) {
        r.insert(std::make_pair(create_dogen_identification_entities_logical_id(position + i), create_boost_shared_ptr_dogen_logical_entities_structural_object_template(position + i)));
    }
    return r;
}

dogen::logical::entities::structural::builtin*
create_dogen_logical_entities_structural_builtin_ptr(const unsigned int position) {
    return dogen::logical::entities::structural::builtin_generator::create_ptr(position);
}

boost::shared_ptr<dogen::logical::entities::structural::builtin>
create_boost_shared_ptr_dogen_logical_entities_structural_builtin(unsigned int position) {
    boost::shared_ptr<dogen::logical::entities::structural::builtin> r(
        create_dogen_logical_entities_structural_builtin_ptr(position));
    return r;
}

std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::builtin> > create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_builtin(unsigned int position) {
    std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::builtin> > r;
    for (unsigned int i(0); i < 4; ++i) {
        r.insert(std::make_pair(create_dogen_identification_entities_logical_id(position + i), create_boost_shared_ptr_dogen_logical_entities_structural_builtin(position + i)));
    }
    return r;
}

dogen::logical::entities::structural::enumeration*
create_dogen_logical_entities_structural_enumeration_ptr(const unsigned int position) {
    return dogen::logical::entities::structural::enumeration_generator::create_ptr(position);
}

boost::shared_ptr<dogen::logical::entities::structural::enumeration>
create_boost_shared_ptr_dogen_logical_entities_structural_enumeration(unsigned int position) {
    boost::shared_ptr<dogen::logical::entities::structural::enumeration> r(
        create_dogen_logical_entities_structural_enumeration_ptr(position));
    return r;
}

std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::enumeration> > create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_enumeration(unsigned int position) {
    std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::enumeration> > r;
    for (unsigned int i(0); i < 4; ++i) {
        r.insert(std::make_pair(create_dogen_identification_entities_logical_id(position + i), create_boost_shared_ptr_dogen_logical_entities_structural_enumeration(position + i)));
    }
    return r;
}

dogen::logical::entities::structural::primitive*
create_dogen_logical_entities_structural_primitive_ptr(const unsigned int position) {
    return dogen::logical::entities::structural::primitive_generator::create_ptr(position);
}

boost::shared_ptr<dogen::logical::entities::structural::primitive>
create_boost_shared_ptr_dogen_logical_entities_structural_primitive(unsigned int position) {
    boost::shared_ptr<dogen::logical::entities::structural::primitive> r(
        create_dogen_logical_entities_structural_primitive_ptr(position));
    return r;
}

std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::primitive> > create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_primitive(unsigned int position) {
    std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::primitive> > r;
    for (unsigned int i(0); i < 4; ++i) {
        r.insert(std::make_pair(create_dogen_identification_entities_logical_id(position + i), create_boost_shared_ptr_dogen_logical_entities_structural_primitive(position + i)));
    }
    return r;
}

dogen::logical::entities::structural::object*
create_dogen_logical_entities_structural_object_ptr(const unsigned int position) {
    return dogen::logical::entities::structural::object_generator::create_ptr(position);
}

boost::shared_ptr<dogen::logical::entities::structural::object>
create_boost_shared_ptr_dogen_logical_entities_structural_object(unsigned int position) {
    boost::shared_ptr<dogen::logical::entities::structural::object> r(
        create_dogen_logical_entities_structural_object_ptr(position));
    return r;
}

std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::object> > create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_object(unsigned int position) {
    std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::object> > r;
    for (unsigned int i(0); i < 4; ++i) {
        r.insert(std::make_pair(create_dogen_identification_entities_logical_id(position + i), create_boost_shared_ptr_dogen_logical_entities_structural_object(position + i)));
    }
    return r;
}

dogen::logical::entities::structural::exception*
create_dogen_logical_entities_structural_exception_ptr(const unsigned int position) {
    return dogen::logical::entities::structural::exception_generator::create_ptr(position);
}

boost::shared_ptr<dogen::logical::entities::structural::exception>
create_boost_shared_ptr_dogen_logical_entities_structural_exception(unsigned int position) {
    boost::shared_ptr<dogen::logical::entities::structural::exception> r(
        create_dogen_logical_entities_structural_exception_ptr(position));
    return r;
}

std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::exception> > create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_exception(unsigned int position) {
    std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::exception> > r;
    for (unsigned int i(0); i < 4; ++i) {
        r.insert(std::make_pair(create_dogen_identification_entities_logical_id(position + i), create_boost_shared_ptr_dogen_logical_entities_structural_exception(position + i)));
    }
    return r;
}

dogen::logical::entities::structural::visitor*
create_dogen_logical_entities_structural_visitor_ptr(const unsigned int position) {
    return dogen::logical::entities::structural::visitor_generator::create_ptr(position);
}

boost::shared_ptr<dogen::logical::entities::structural::visitor>
create_boost_shared_ptr_dogen_logical_entities_structural_visitor(unsigned int position) {
    boost::shared_ptr<dogen::logical::entities::structural::visitor> r(
        create_dogen_logical_entities_structural_visitor_ptr(position));
    return r;
}

std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::visitor> > create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_visitor(unsigned int position) {
    std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::visitor> > r;
    for (unsigned int i(0); i < 4; ++i) {
        r.insert(std::make_pair(create_dogen_identification_entities_logical_id(position + i), create_boost_shared_ptr_dogen_logical_entities_structural_visitor(position + i)));
    }
    return r;
}

dogen::logical::entities::structural::entry_point*
create_dogen_logical_entities_structural_entry_point_ptr(const unsigned int position) {
    return dogen::logical::entities::structural::entry_point_generator::create_ptr(position);
}

boost::shared_ptr<dogen::logical::entities::structural::entry_point>
create_boost_shared_ptr_dogen_logical_entities_structural_entry_point(unsigned int position) {
    boost::shared_ptr<dogen::logical::entities::structural::entry_point> r(
        create_dogen_logical_entities_structural_entry_point_ptr(position));
    return r;
}

std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::entry_point> > create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_entry_point(unsigned int position) {
    std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::entry_point> > r;
    for (unsigned int i(0); i < 4; ++i) {
        r.insert(std::make_pair(create_dogen_identification_entities_logical_id(position + i), create_boost_shared_ptr_dogen_logical_entities_structural_entry_point(position + i)));
    }
    return r;
}

dogen::logical::entities::structural::assistant*
create_dogen_logical_entities_structural_assistant_ptr(const unsigned int position) {
    return dogen::logical::entities::structural::assistant_generator::create_ptr(position);
}

boost::shared_ptr<dogen::logical::entities::structural::assistant>
create_boost_shared_ptr_dogen_logical_entities_structural_assistant(unsigned int position) {
    boost::shared_ptr<dogen::logical::entities::structural::assistant> r(
        create_dogen_logical_entities_structural_assistant_ptr(position));
    return r;
}

std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::assistant> > create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_assistant(unsigned int position) {
    std::unordered_map<dogen::identification::entities::logical_id, boost::shared_ptr<dogen::logical::entities::structural::assistant> > r;
    for (unsigned int i(0); i < 4; ++i) {
        r.insert(std::make_pair(create_dogen_identification_entities_logical_id(position + i), create_boost_shared_ptr_dogen_logical_entities_structural_assistant(position + i)));
    }
    return r;
}

}

namespace dogen::logical::entities::structural {

element_repository_generator::element_repository_generator() : position_(0) { }

void element_repository_generator::
populate(const unsigned int position, result_type& v) {
    v.modules(create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_module(position + 0));
    v.object_templates(create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_object_template(position + 1));
    v.builtins(create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_builtin(position + 2));
    v.enumerations(create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_enumeration(position + 3));
    v.primitives(create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_primitive(position + 4));
    v.objects(create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_object(position + 5));
    v.exceptions(create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_exception(position + 6));
    v.visitors(create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_visitor(position + 7));
    v.entry_points(create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_entry_point(position + 8));
    v.assistants(create_std_unordered_map_dogen_identification_entities_logical_id_boost_shared_ptr_dogen_logical_entities_structural_assistant(position + 9));
}

element_repository_generator::result_type
element_repository_generator::create(const unsigned int position) {
    element_repository r;
    element_repository_generator::populate(position, r);
    return r;
}

element_repository_generator::result_type*
element_repository_generator::create_ptr(const unsigned int position) {
    element_repository* p = new element_repository();
    element_repository_generator::populate(position, *p);
    return p;
}

element_repository_generator::result_type
element_repository_generator::operator()() {
    return create(position_++);
}

}
