@startuml
set namespaceSeparator ::
class schema_document #F7E5FF {
        +{field} id_keyword std::string
        +{field} schema_keyword std::string
        +{field} title std::string
        +{field} type type
        +{field} description std::string
}

enum type <<masd::enumeration>> #F2DAFD {
        +{field} object
        +{field} array
        +{field} string
        +{field} number
        +{field} boolean
        +{field} null
}

class properties #F7E5FF {
        +{field} type type
        +{field} minimum unsigned int
        +{field} maximum unsigned int
        +{field} description std::string
}

class value #F7E5FF {
}

class object #F7E5FF {
}

value <|-- object
class array #F7E5FF {
}

value <|-- array
class string #F7E5FF {
}

value <|-- string
class number #F7E5FF {
}

value <|-- number
class boolean #F7E5FF {
}

value <|-- boolean
@enduml
