@startuml
set namespaceSeparator ::
class document #F7E5FF {
        +{field} openapi std::string
        +{field} info info
        +{field} servers std::list<server>
        +{field} paths paths
        +{field} components components
        +{field} security security_requirements
        +{field} tags tags
        +{field} external_docs external_documentation
}

class info #F7E5FF {
        +{field} title std::string
        +{field} description std::string
        +{field} terms_of_service std::string
        +{field} contact contact
        +{field} license license
        +{field} version std::string
}

class server #F7E5FF {
        +{field} url std::string
        +{field} description std::string
        +{field} variables std::unordered_map<std::string, server_variable>
}

class paths #F7E5FF {
}

class components #F7E5FF {
        +{field} schemas std::unordered_map<std::string, schema>
        +{field} responses std::unordered_map<std::string, response>
        +{field} parameters std::unordered_map<std::string, parameter>
        +{field} examples std::unordered_map<std::string, example>
        +{field} request_bodies std::unordered_map<std::string, request_body>
        +{field} headers std::unordered_map<std::string, request_header>
        +{field} security_schemes std::unordered_map<std::string, security_scheme>
        +{field} links std::unordered_map<std::string, link>
        +{field} callbacks std::unordered_map<std::string, callback>
}

class security_requirements #F7E5FF {
}

class tags #F7E5FF {
}

class externalDocs #F7E5FF {
}

class external_documentation #F7E5FF {
}

class contact #F7E5FF {
        +{field} name std::string
        +{field} url std::string
        +{field} email std::string
}

class licence #F7E5FF {
        +{field} name std::string
        +{field} url std::string
}

class server_variable #F7E5FF {
        +{field} enumeration std::list<std::string>
        +{field} default_value std::string
        +{field} description std::string
}

class schema #F7E5FF {
}

@enduml
