/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * These files are code-generated via overrides to test dogen. Do not commit them.
 *
 * Generation timestamp: 2022-10-20T10:20:30
 * WARNING: do not edit this file manually.
 * Generated by MASD Dogen v1.0.33
 *
 * Copyright (C) 2012-2015 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 */
#include <sstream>
#include "dogen.logical/test_data/entities/model_td.hpp"
#include "dogen.logical/test_data/entities/input_model_set_td.hpp"

namespace {

dogen::logical::entities::model
create_dogen_logical_entities_model(const unsigned int position) {
    return dogen::logical::entities::model_generator::create(position);
}

std::list<dogen::logical::entities::model> create_std_list_dogen_logical_entities_model(unsigned int position) {
    std::list<dogen::logical::entities::model> r;
    for (unsigned int i(0); i < 4; ++i) {
        r.push_back(create_dogen_logical_entities_model(position + i));
    }
    return r;
}

std::string create_std_string(const unsigned int position) {
    std::ostringstream s;
    s << "a_string_" << position;
    return s.str();
}

std::unordered_map<std::string, std::string> create_std_unordered_map_std_string_std_string(unsigned int position) {
    std::unordered_map<std::string, std::string> r;
    for (unsigned int i(0); i < 4; ++i) {
        r.insert(std::make_pair(create_std_string(position + i), create_std_string(position + i)));
    }
    return r;
}

}

namespace dogen::logical::entities {

input_model_set_generator::input_model_set_generator() : position_(0) { }

void input_model_set_generator::
populate(const unsigned int position, result_type& v) {
    v.target(create_dogen_logical_entities_model(position + 0));
    v.references(create_std_list_dogen_logical_entities_model(position + 1));
    v.fixed_mappings(create_std_unordered_map_std_string_std_string(position + 2));
}

input_model_set_generator::result_type
input_model_set_generator::create(const unsigned int position) {
    input_model_set r;
    input_model_set_generator::populate(position, r);
    return r;
}

input_model_set_generator::result_type*
input_model_set_generator::create_ptr(const unsigned int position) {
    input_model_set* p = new input_model_set();
    input_model_set_generator::populate(position, *p);
    return p;
}

input_model_set_generator::result_type
input_model_set_generator::operator()() {
    return create(position_++);
}

}
