/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * These files are code-generated via overrides to test dogen. Do not commit them.
 *
 * Generation timestamp: 2022-10-20T10:20:30
 * WARNING: do not edit this file manually.
 * Generated by MASD Dogen v1.0.33
 *
 * Copyright (C) 2012-2015 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 */
#ifndef DOGEN_LOGICAL_TYPES_ENTITIES_ORM_ODB_TARGETS_HPP
#define DOGEN_LOGICAL_TYPES_ENTITIES_ORM_ODB_TARGETS_HPP

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
#pragma once
#endif

#include <list>
#include <string>
#include <algorithm>
#include "dogen.logical/types/entities/orm/odb_target.hpp"
#include "dogen.logical/serialization/entities/orm/odb_targets_fwd_ser.hpp"

namespace dogen::logical::entities::orm {

class odb_targets final {
public:
    odb_targets() = default;
    odb_targets(const odb_targets&) = default;
    odb_targets(odb_targets&&) = default;
    ~odb_targets() = default;

public:
    odb_targets(
        const std::string& main_target_name,
        const std::string& common_odb_options,
        const std::list<dogen::logical::entities::orm::odb_target>& targets);

private:
    template<typename Archive>
    friend void boost::serialization::save(Archive& ar, const dogen::logical::entities::orm::odb_targets& v, unsigned int version);

    template<typename Archive>
    friend void boost::serialization::load(Archive& ar, dogen::logical::entities::orm::odb_targets& v, unsigned int version);

public:
    const std::string& main_target_name() const;
    std::string& main_target_name();
    void main_target_name(const std::string& v);
    void main_target_name(const std::string&& v);

    const std::string& common_odb_options() const;
    std::string& common_odb_options();
    void common_odb_options(const std::string& v);
    void common_odb_options(const std::string&& v);

    const std::list<dogen::logical::entities::orm::odb_target>& targets() const;
    std::list<dogen::logical::entities::orm::odb_target>& targets();
    void targets(const std::list<dogen::logical::entities::orm::odb_target>& v);
    void targets(const std::list<dogen::logical::entities::orm::odb_target>&& v);

public:
    bool operator==(const odb_targets& rhs) const;
    bool operator!=(const odb_targets& rhs) const {
        return !this->operator==(rhs);
    }

public:
    void swap(odb_targets& other) noexcept;
    odb_targets& operator=(odb_targets other);

private:
    std::string main_target_name_;
    std::string common_odb_options_;
    std::list<dogen::logical::entities::orm::odb_target> targets_;
};

}

namespace std {

template<>
inline void swap(
    dogen::logical::entities::orm::odb_targets& lhs,
    dogen::logical::entities::orm::odb_targets& rhs) {
    lhs.swap(rhs);
}

}

#endif
