#+title: Sprint Backlog 35
#+options: date:nil toc:nil author:nil num:nil
#+todo: ANALYSIS IMPLEMENTATION TESTING | COMPLETED CANCELLED
#+tags: story(s) epic(e) task(t) note(n) spike(p)

* Stories

This file contains all stories that were closed during sprint 35.

** Development Stories Implemented

#+begin: clocktable :maxlevel 3 :scope subtree
Clock summary at [2014-05-27 Tue 13:04]

| Headline                                                                 | Time    |       |       |
|--------------------------------------------------------------------------+---------+-------+-------|
| *Total time*                                                             | *36:54* |       |       |
|--------------------------------------------------------------------------+---------+-------+-------|
| Development Stories Implemented                                          |         | 36:54 |       |
| COMPLETED Sprint and product backlog grooming                            |         |       |  0:39 |
| COMPLETED Refactor OM tests to avoid over-inclusion                      |         |       |  0:32 |
| COMPLETED Convert implementation specific parameters to list             |         |       |  1:06 |
| COMPLETED Rename implementation specific parameters                      |         |       |  0:50 |
| COMPLETED Add meta-data support to SML                                   |         |       |  5:04 |
| COMPLETED Fix includes in SML tests                                      |         |       |  0:42 |
| COMPLETED Create an hydrator from JSON into SML                          |         |       |  3:53 |
| COMPLETED Replace static factories for system models with json hydration |         |       |  1:41 |
| COMPLETED Rename domain header formatter to types header formatter       |         |       |  0:13 |
| COMPLETED Create a complete domain formatter in OM                       |         |       | 10:42 |
| COMPLETED Implement model tagger                                         |         |       | 10:18 |
| CANCELLED Implement the property cache in SML                            |         |       |  1:14 |
#+end:

*** COMPLETED Sprint and product backlog grooming                      :task:
    CLOSED: [2013-10-07 Mon 18:00]
    CLOCK: [2013-09-30 Mon 17:58]--[2013-09-30 Mon 18:25] =>  0:22
    CLOCK: [2013-09-23 Mon 07:50]--[2013-09-23 Mon 08:02] =>  0:12

*** COMPLETED Refactor OM tests to avoid over-inclusion               :spike:
    CLOSED: [2013-09-23 Mon 23:41]
    CLOCK: [2013-09-23 Mon 23:05]--[2013-09-23 Mon 23:37] =>  0:32

At present OM builds take too long on slow hardware because we are
using the facet includers in tests. This means that every time a
service changes one has to rebuild all the specs in OM. Include all
the types manually in unit tests to reduce the dependencies.

*** COMPLETED Convert implementation specific parameters to list      :spike:
    CLOSED: [2013-09-24 Tue 22:49]
    CLOCK: [2013-09-24 Tue 23:19]--[2013-09-24 Tue 23:36] =>  0:17
    CLOCK: [2013-09-24 Tue 22:49]--[2013-09-24 Tue 23:19] =>  0:30
    CLOCK: [2013-09-24 Tue 17:56]--[2013-09-24 Tue 18:08] =>  0:12
    CLOCK: [2013-09-24 Tue 08:13]--[2013-09-24 Tue 08:20] =>  0:07

We need to do lookups into the parameters, so a vector is not
suitable. change it to a =std::unordered_map=.

Actually, It is not possible to do this due to the way ODB parameters
work; we need to maintain the order defined by the user (and it needs
to allow for duplicates). However, might as well use a =std::list= instead of
a =std::vector=.

*** COMPLETED Rename implementation specific parameters               :story:
    CLOSED: [2013-09-24 Tue 18:33]
    CLOCK: [2013-09-24 Tue 22:27]--[2013-09-24 Tue 22:49] =>  0:22
    CLOCK: [2013-09-24 Tue 18:12]--[2013-09-24 Tue 18:40] =>  0:28

These should really be called back end specific parameters at the SML
level. At the dia level, if a parameter is passed in which has a
representation at the SML level it should simply be converted to this
representation instead of being added to the KVP.

Actually, these are more like generic parameters:

- at the dia level they are used to fill in gaps in dia (e.g. packages
  and diagrams do not have comments)
- at the SML level, they are used to add information which does not
  make sense for it to be in dia: is property key.
- at the backend level, they are used to provide information which
  does not make sense to live in SML: for example the ODB parameters.

Also, when the string table support has been added, we need to create
a string table with all valid values for the parameter keys.

Name choices:

- opaque parameters
- untyped parameters

*** COMPLETED Add meta-data support to SML                            :story:
    CLOSED: [2013-09-27 Fri 23:42]
    CLOCK: [2013-09-27 Fri 21:10]--[2013-09-27 Fri 23:10] =>  2:00
    CLOCK: [2013-09-27 Fri 08:21]--[2013-09-27 Fri 08:30] =>  0:09
    CLOCK: [2013-09-27 Fri 07:48]--[2013-09-27 Fri 08:13] =>  0:25
    CLOCK: [2013-09-26 Thu 22:31]--[2013-09-26 Thu 23:31] =>  1:00
    CLOCK: [2013-09-26 Thu 22:25]--[2013-09-26 Thu 22:31] =>  0:06
    CLOCK: [2013-09-26 Thu 19:11]--[2013-09-26 Thu 19:18] =>  0:07
    CLOCK: [2013-09-26 Thu 18:22]--[2013-09-26 Thu 18:43] =>  0:21
    CLOCK: [2013-09-25 Wed 18:02]--[2013-09-25 Wed 18:53] =>  0:51
    CLOCK: [2013-09-25 Wed 17:57]--[2013-09-25 Wed 18:02] =>  0:05

New understanding:

There is a fundamental problem with the parameter cache approach: it
does not take into account parameters in properties. If we were to
create another layer in the cache, we would be duplicating the object
graph that we already have in =abstract_object= so the entire idea is
questionable.

A much better way of doing this is to create two types of parameters:

- sequence: odb pragmas
- associative: everything else

Also, parameters are really some kind of meta-data tag, so we should
rename it to avoid confusion. So we have:

- =tag_store=: place where all tags live. we should add methods for easy
  tag retrieval with the right type.
- =Taggable=: concept for those which have the ability of being tagged.
- =tags=: property of Taggable entities.
- =tag_router=: takes a pair of strings and routes it to the right
  location on the =tag_store=.
- =tagger=: visits the model as a graph and propagates tags across
  generalisations and associations.

Old understanding:

create a opaque parameter cache in SML.

*** COMPLETED Fix includes in SML tests                               :spike:
    CLOSED: [2013-09-30 Mon 19:36]
    CLOCK: [2013-09-30 Mon 18:25]--[2013-09-30 Mon 18:52] =>  0:27
    CLOCK: [2013-09-30 Mon 17:40]--[2013-09-30 Mon 17:55] =>  0:15

At present we are using the facet includers in SML which results in
really long compilations everytime we change a service. Manually fix
the tests to only include the required objects.

*** COMPLETED Create an hydrator from JSON into SML                   :story:
    CLOSED: [2013-10-01 Tue 00:19]
    CLOCK: [2013-10-01 Tue 08:24]--[2013-10-01 Tue 08:37] =>  0:13
    CLOCK: [2013-10-01 Tue 07:49]--[2013-10-01 Tue 08:19] =>  0:30
    CLOCK: [2013-10-01 Tue 07:38]--[2013-10-01 Tue 07:45] =>  0:07
    CLOCK: [2013-10-01 Tue 00:03]--[2013-10-01 Tue 00:19] =>  0:16
    CLOCK: [2013-09-30 Mon 23:21]--[2013-10-01 Tue 00:03] =>  0:42
    CLOCK: [2013-09-30 Mon 22:55]--[2013-09-30 Mon 23:20] =>  0:25
    CLOCK: [2013-09-29 Sun 19:34]--[2013-09-29 Sun 21:05] =>  1:31
    CLOCK: [2013-09-29 Sun 19:25]--[2013-09-29 Sun 19:34] =>  0:09

Using the JSON representation defined in the previous iteration (in
data/library) and boost property tree, create an hydrator/transformer
that generates SML models.

*** COMPLETED Replace static factories for system models with json hydration :story:
    CLOSED: [2013-10-02 Wed 08:37]
    CLOCK: [2013-10-02 Wed 08:30]--[2013-10-02 Wed 08:36] =>  0:06
    CLOCK: [2013-10-02 Wed 07:46]--[2013-10-02 Wed 08:20] =>  0:34
    CLOCK: [2013-10-02 Wed 07:33]--[2013-10-02 Wed 07:44] =>  0:11
    CLOCK: [2013-10-01 Tue 22:04]--[2013-10-01 Tue 22:35] =>  0:31
    CLOCK: [2013-10-01 Tue 18:20]--[2013-10-01 Tue 18:30] =>  0:10
    CLOCK: [2013-10-01 Tue 18:01]--[2013-10-01 Tue 18:10] =>  0:09

*** COMPLETED Rename domain header formatter to types header formatter :spike:
    CLOSED: [2013-10-05 Sat 18:18]
    CLOCK: [2013-10-05 Sat 18:05]--[2013-10-05 Sat 18:18] =>  0:13

The name should reflect the facet name.

**** Propagatable parameters                                          :story:

Some implementation specific parameters should be propagated along the
composition graph (e.g. boost serialisation status disabled). We could
spot these parameters whilst building the model and do the propagation
there and then.

We need to create language specific classes to propagate parameters,
assign proper defaults to them, etc.

*** COMPLETED Create a complete domain formatter in OM                :story:
    CLOSED: [2013-10-07 Mon 18:01]
    CLOCK: [2013-09-26 Thu 22:08]--[2013-09-26 Thu 22:25] =>  0:17
    CLOCK: [2013-09-26 Thu 08:25]--[2013-09-26 Thu 08:33] =>  0:08
    CLOCK: [2013-09-26 Thu 08:06]--[2013-09-26 Thu 08:18] =>  0:12
    CLOCK: [2013-09-26 Thu 07:46]--[2013-09-26 Thu 08:06] =>  0:20
    CLOCK: [2013-09-23 Mon 18:20]--[2013-09-23 Mon 18:50] =>  0:30
    CLOCK: [2013-09-23 Mon 18:12]--[2013-09-23 Mon 18:17] =>  0:05
    CLOCK: [2013-09-23 Mon 17:56]--[2013-09-23 Mon 18:05] =>  0:09
    CLOCK: [2013-09-23 Mon 08:02]--[2013-09-23 Mon 08:15] =>  0:13

The OM domain formatter must produce the same code as the C++
formatter across all types. Add all infrastructure around it such as
SML type visitors, etc.

**** COMPLETED Implement class open and close methods                  :task:
     CLOSED: [2013-09-23 Mon 23:54]
     CLOCK: [2013-09-23 Mon 23:43]--[2013-09-23 Mon 23:54] =>  0:11

**** COMPLETED Refactor unit tests with utility method                 :task:
     CLOSED: [2013-09-24 Tue 08:05]
     CLOCK: [2013-09-24 Tue 07:46]--[2013-09-24 Tue 08:10] =>  0:19
     CLOCK: [2013-09-24 Tue 07:33]--[2013-09-24 Tue 07:43] =>  0:18

**** COMPLETED Add compiler generated constructors                     :task:
     CLOSED: [2013-09-28 Sat 20:25]
     CLOCK: [2013-09-28 Sat 15:34]--[2013-09-28 Sat 17:07] =>  1:33
     CLOCK: [2013-09-28 Sat 15:02]--[2013-09-28 Sat 15:34] =>  0:32
     CLOCK: [2013-09-28 Sat 14:59]--[2013-09-28 Sat 15:02] =>  0:03
     CLOCK: [2013-09-28 Sat 11:02]--[2013-09-28 Sat 11:06] =>  0:04
     CLOCK: [2013-09-27 Fri 23:10]--[2013-09-28 Sat 00:11] =>  1:01
**** COMPLETED Add remaining meta-data required to finish domain formatter :task:
     CLOSED: [2013-09-28 Sat 22:53]
     CLOCK: [2013-09-28 Sat 20:26]--[2013-09-28 Sat 22:53] =>  2:27

**** COMPLETED Clean up tag adaptor API
     CLOSED: [2013-09-29 Sun 01:41]
     CLOCK: [2013-09-29 Sun 01:41]--[2013-09-29 Sun 01:50] =>  0:09
     CLOCK: [2013-09-29 Sun 00:10]--[2013-09-29 Sun 01:40] =>  1:30

**** CANCELLED Add tests for all permutations of the domain formatter  :task:
     CLOSED: [2013-10-07 Mon 18:01]
     CLOCK: [2013-09-28 Sat 23:16]--[2013-09-28 Sat 23:37] =>  0:21
     CLOCK: [2013-09-28 Sat 22:53]--[2013-09-28 Sat 23:16] =>  0:23

*** COMPLETED Implement model tagger                                  :story:
    CLOSED: [2013-10-07 Mon 18:02]
    CLOCK: [2013-10-05 Sat 11:16]--[2013-10-05 Sat 11:38] =>  0:22
    CLOCK: [2013-10-03 Thu 17:40]--[2013-10-03 Thu 17:51] =>  0:11
    CLOCK: [2013-10-03 Thu 17:31]--[2013-10-03 Thu 17:38] =>  0:20
    CLOCK: [2013-10-03 Thu 07:22]--[2013-10-03 Thu 07:29] =>  0:07
    CLOCK: [2013-10-03 Thu 07:17]--[2013-10-03 Thu 07:21] =>  0:04
    CLOCK: [2013-10-03 Thu 07:00]--[2013-10-03 Thu 07:13] =>  0:13
    CLOCK: [2013-10-03 Thu 06:40]--[2013-10-03 Thu 07:00] =>  0:20
    CLOCK: [2013-10-03 Thu 06:32]--[2013-10-03 Thu 06:37] =>  0:05
    CLOCK: [2013-10-02 Wed 17:40]--[2013-10-02 Wed 17:57] =>  0:17
    CLOCK: [2013-10-02 Wed 17:26]--[2013-10-02 Wed 17:35] =>  0:09
    CLOCK: [2013-09-29 Sun 18:43]--[2013-09-29 Sun 19:25] =>  0:42
    CLOCK: [2013-09-29 Sun 18:23]--[2013-09-29 Sun 18:43] =>  0:20
    CLOCK: [2013-09-29 Sun 01:50]--[2013-09-29 Sun 02:08] =>  0:18
    CLOCK: [2013-09-29 Sun 00:01]--[2013-09-29 Sun 00:10] =>  0:09
    CLOCK: [2013-09-28 Sat 15:34]--[2013-09-28 Sat 17:07] =>  1:33
    CLOCK: [2013-09-28 Sat 15:02]--[2013-09-28 Sat 15:34] =>  0:32
    CLOCK: [2013-09-28 Sat 14:59]--[2013-09-28 Sat 15:02] =>  0:03
    CLOCK: [2013-09-28 Sat 11:02]--[2013-09-28 Sat 11:06] =>  0:04

**** COMPLETED Split tags for files for each file type                 :task:
     CLOSED: [2013-10-05 Sat 15:43]
     CLOCK: [2013-10-05 Sat 14:27]--[2013-10-05 Sat 15:42] =>  1:15

**** COMPLETED Add tagging from config as way of keeping backwards compatibility :task:
     CLOSED: [2013-10-06 Sun 01:41]
     CLOCK: [2013-10-06 Sun 00:11]--[2013-10-06 Sun 01:41] =>  1:30

**** CANCELLED Add tests around model tagging                          :task:
     CLOSED: [2013-10-07 Mon 18:02]
     CLOCK: [2013-10-06 Sun 12:25]--[2013-10-06 Sun 13:16] =>  0:51
     CLOCK: [2013-10-06 Sun 12:23]--[2013-10-06 Sun 12:24] =>  0:01
     CLOCK: [2013-10-06 Sun 12:05]--[2013-10-06 Sun 12:23] =>  0:18

**** CANCELLED Add tagging for types                                   :task:
     CLOSED: [2013-10-07 Mon 18:02]
     CLOCK: [2013-10-06 Sun 00:02]--[2013-10-06 Sun 00:10] =>  0:08
     CLOCK: [2013-10-05 Sat 21:10]--[2013-10-05 Sat 21:20] =>  0:10
     CLOCK: [2013-10-05 Sat 20:27]--[2013-10-05 Sat 20:56] =>  0:29

*** CANCELLED Implement the property cache in SML                     :story:
    CLOSED: [2013-10-07 Mon 18:02]
    CLOCK: [2013-09-25 Wed 08:09]--[2013-09-25 Wed 08:17] =>  0:08
    CLOCK: [2013-09-25 Wed 07:47]--[2013-09-25 Wed 08:09] =>  0:22
    CLOCK: [2013-09-24 Tue 23:40]--[2013-09-25 Wed 00:24] =>  0:44

** Deprecated Development Stories
