#+title: Release Notes for Sprint 23
#+options: date:nil toc:nil author:nil num:nil
#+todo: ANALYSIS IMPLEMENTATION TESTING | COMPLETED CANCELLED
#+tags: story(s) epic(e) task(t) note(n) spike(p)

* Release Notes

This file contains all stories that were closed during sprint 23.

** Development Stories Implemented

#+begin: clocktable :maxlevel 3 :scope subtree
#+end:

*** COMPLETED Before throwing write exception to log file             :story:
    CLOSED: [2012-12-17 Mon 17:15]

We have cases were an exception is thrown and its impossible to figure
out where. If we logged before throw we'd have all the context.

Implemented by RP.

*** COMPLETED Forward declaration of enumerations is incorrect        :story:

When including forward declarations of enums the following error comes
up:

: relative_position_types_fwd.hpp:31:12: error: different underlying type in enum ‘enum class creris::rating::relative_position_types’

Seems like the compiler is either declaring the enumeration (rather
than forward declaring it) or the forward declaration requires an
underlying type.

MC: According to wikipedia, the default type of a C++-11 enumeration
is =int=:

http://en.wikipedia.org/wiki/C%2B%2B11#Strongly_typed_enumerations

We need to specify the type when we forward declare.

** Deprecated Development Stories
