#+title: Release Notes for Sprint 21
#+options: date:nil toc:nil author:nil num:nil
#+todo: ANALYSIS IMPLEMENTATION TESTING | COMPLETED CANCELLED
#+tags: story(s) epic(e) task(t) note(n) spike(p)

* Release Notes

This file contains all stories that were closed during sprint 21.

** Development Stories Implemented


#+begin: clocktable :maxlevel 3 :scope subtree
Clock summary at [2012-11-21 Wed 16:34]

| Headline     | Time   |
|--------------+--------|
| *Total time* | *0:00* |
#+end:

*** Mix-and-match of manual types

When adding types manually one needs to add a regex to get dogen to
ignore these files. This works but it means dogen does not add these
files to the includers. A better solution would be to add a stereotype
of =manual= which would result in automatic ignoring of files for
these types as well as adding them to includers.

*** COMPLETED Reduce size of doxygen packages
    CLOSED: [2012-11-21 Wed 16:37]

We need to investigate our doxygen configuration to figure out why our
doxygen packages are so large - weighing at 350MB at the moment, they
are too large to be uploaded to github. We need to find other
project's doxygen configuration to figure out what we are doing wrong.

The main problem must be related to PNG generation.



** Deprecated Development Stories
