#+title: Release Notes for Sprint 21
#+options: date:nil toc:nil author:nil num:nil
#+todo: ANALYSIS IMPLEMENTATION TESTING | COMPLETED CANCELLED
#+tags: story(s) epic(e) task(t) note(n) spike(p)

* Release Notes

This file contains all stories that were closed during sprint 21.

** Development Stories Implemented


#+begin: clocktable :maxlevel 3 :scope subtree
Clock summary at [2012-11-21 Wed 16:34]

| Headline     | Time   |
|--------------+--------|
| *Total time* | *0:00* |
#+end:

*** Mix-and-match of manual types

When adding types manually one needs to add a regex to get dogen to
ignore these files. This works but it means dogen does not add these
files to the includers. A better solution would be to add a stereotype
of =manual= which would result in automatic ignoring of files for
these types as well as adding them to includers.

*** Add support for _manual_ types

Sometimes one requires data structures which are just too complicated
for code generation, such as =boost::multi_index=. In this cases one
should add these domain types manually, together with their
serialisation, etc. However, if one then wants to make use of these
types from trivial types, the code generator will fail to resolve. We
need a stereotype of _manual_ (or some such name) which allows the
type to be declared to the type system but no further processing
(including generation) will occur.

*** COMPLETED Reduce size of doxygen packages
    CLOSED: [2012-11-21 Wed 16:37]

We need to investigate our doxygen configuration to figure out why our
doxygen packages are so large - weighing at 350MB at the moment, they
are too large to be uploaded to github. We need to find other
project's doxygen configuration to figure out what we are doing wrong.

The main problem must be related to PNG generation.



** Deprecated Development Stories
