/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * These files are code-generated via overrides to test dogen. Do not commit them.
 *
 * Generation timestamp: 2022-10-20T10:20:30
 * WARNING: do not edit this file manually.
 * Generated by MASD Dogen v1.0.33
 *
 * Copyright (C) 2012-2015 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 */
#include "dogen.identification/hash/entities/logical_meta_id_hash.hpp"
#include "dogen.identification/hash/entities/technical_space_hash.hpp"
#include "dogen.identification/hash/entities/physical_meta_id_hash.hpp"
#include "dogen.identification/hash/entities/archetype_name_set_hash.hpp"
#include "dogen.identification/hash/entities/physical_meta_name_hash.hpp"
#include "dogen.identification/hash/entities/physical_meta_name_indices_hash.hpp"

namespace {

template <typename HashableType>
inline void combine(std::size_t& seed, const HashableType& value) {
    std::hash<HashableType> hasher;
    seed ^= hasher(value) + 0x9e3779b9 + (seed << 6) + (seed >> 2);
}

inline std::size_t hash_std_list_dogen_identification_entities_physical_meta_name(const std::list<dogen::identification::entities::physical_meta_name>& v) {
    std::size_t seed(0);
    for (const auto& i : v) {
        combine(seed, i);
    }
    return seed;
}

inline std::size_t hash_std_unordered_set_dogen_identification_entities_physical_meta_id(const std::unordered_set<dogen::identification::entities::physical_meta_id>& v) {
    std::size_t seed(0);
    for (const auto& i : v) {
        combine(seed, i);
    }
    return seed;
}

inline std::size_t hash_std_unordered_map_dogen_identification_entities_physical_meta_id_std_unordered_set_dogen_identification_entities_physical_meta_id(const std::unordered_map<dogen::identification::entities::physical_meta_id, std::unordered_set<dogen::identification::entities::physical_meta_id> >& v) {
    std::size_t seed(0);
    for (const auto& i : v) {
        combine(seed, i.first);
        combine(seed, hash_std_unordered_set_dogen_identification_entities_physical_meta_id(i.second));
    }
    return seed;
}

inline std::size_t hash_std_unordered_map_dogen_identification_entities_logical_meta_id_dogen_identification_entities_archetype_name_set(const std::unordered_map<dogen::identification::entities::logical_meta_id, dogen::identification::entities::archetype_name_set>& v) {
    std::size_t seed(0);
    for (const auto& i : v) {
        combine(seed, i.first);
        combine(seed, i.second);
    }
    return seed;
}

inline std::size_t hash_std_list_dogen_identification_entities_physical_meta_id(const std::list<dogen::identification::entities::physical_meta_id>& v) {
    std::size_t seed(0);
    for (const auto& i : v) {
        combine(seed, i);
    }
    return seed;
}

inline std::size_t hash_std_unordered_map_dogen_identification_entities_physical_meta_id_std_list_dogen_identification_entities_physical_meta_id(const std::unordered_map<dogen::identification::entities::physical_meta_id, std::list<dogen::identification::entities::physical_meta_id> >& v) {
    std::size_t seed(0);
    for (const auto& i : v) {
        combine(seed, i.first);
        combine(seed, hash_std_list_dogen_identification_entities_physical_meta_id(i.second));
    }
    return seed;
}

inline std::size_t hash_std_unordered_map_dogen_identification_entities_physical_meta_id_std_unordered_map_dogen_identification_entities_physical_meta_id_std_list_dogen_identification_entities_physical_meta_id(const std::unordered_map<dogen::identification::entities::physical_meta_id, std::unordered_map<dogen::identification::entities::physical_meta_id, std::list<dogen::identification::entities::physical_meta_id> > >& v) {
    std::size_t seed(0);
    for (const auto& i : v) {
        combine(seed, i.first);
        combine(seed, hash_std_unordered_map_dogen_identification_entities_physical_meta_id_std_list_dogen_identification_entities_physical_meta_id(i.second));
    }
    return seed;
}

inline std::size_t hash_std_unordered_map_dogen_identification_entities_physical_meta_id_dogen_identification_entities_technical_space(const std::unordered_map<dogen::identification::entities::physical_meta_id, dogen::identification::entities::technical_space>& v) {
    std::size_t seed(0);
    for (const auto& i : v) {
        combine(seed, i.first);
        combine(seed, i.second);
    }
    return seed;
}

}

namespace dogen::identification::entities {

std::size_t physical_meta_name_indices_hasher::hash(const physical_meta_name_indices& v) {
    std::size_t seed(0);

    combine(seed, hash_std_list_dogen_identification_entities_physical_meta_name(v.all()));
    combine(seed, hash_std_unordered_map_dogen_identification_entities_physical_meta_id_std_unordered_set_dogen_identification_entities_physical_meta_id(v.facet_names_by_backend_name()));
    combine(seed, hash_std_unordered_map_dogen_identification_entities_logical_meta_id_dogen_identification_entities_archetype_name_set(v.archetype_names_by_logical_meta_name()));
    combine(seed, hash_std_unordered_map_dogen_identification_entities_physical_meta_id_std_unordered_map_dogen_identification_entities_physical_meta_id_std_list_dogen_identification_entities_physical_meta_id(v.archetype_names_by_backend_by_facet()));
    combine(seed, hash_std_unordered_map_dogen_identification_entities_physical_meta_id_dogen_identification_entities_technical_space(v.technical_space_for_archetype()));

    return seed;
}

}
