/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * These files are code-generated via overrides to test dogen. Do not commit them.
 *
 * Generation timestamp: 2022-10-20T10:20:30
 * WARNING: do not edit this file manually.
 * Generated by MASD Dogen v1.0.33
 *
 * Copyright (C) 2012-2015 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 */
#include <sstream>
#include "dogen.codec/test_data/entities/comment_td.hpp"
#include "dogen.identification/test_data/entities/tagged_value_td.hpp"

namespace {

dogen::identification::entities::tagged_value
create_dogen_identification_entities_tagged_value(const unsigned int position) {
    return dogen::identification::entities::tagged_value_generator::create(position);
}

std::list<dogen::identification::entities::tagged_value> create_std_list_dogen_identification_entities_tagged_value(unsigned int position) {
    std::list<dogen::identification::entities::tagged_value> r;
    for (unsigned int i(0); i < 4; ++i) {
        r.push_back(create_dogen_identification_entities_tagged_value(position + i));
    }
    return r;
}

bool create_bool(const unsigned int position) {
    return (position % 2) != 0;
}

std::string create_std_string(const unsigned int position) {
    std::ostringstream s;
    s << "a_string_" << position;
    return s.str();
}

}

namespace dogen::codec::entities {

comment_generator::comment_generator() : position_(0) { }

void comment_generator::
populate(const unsigned int position, result_type& v) {
    v.tagged_values(create_std_list_dogen_identification_entities_tagged_value(position + 0));
    v.applies_to_container(create_bool(position + 1));
    v.original_content(create_std_string(position + 2));
    v.documentation(create_std_string(position + 3));
}

comment_generator::result_type
comment_generator::create(const unsigned int position) {
    comment r;
    comment_generator::populate(position, r);
    return r;
}

comment_generator::result_type*
comment_generator::create_ptr(const unsigned int position) {
    comment* p = new comment();
    comment_generator::populate(position, *p);
    return p;
}

comment_generator::result_type
comment_generator::operator()() {
    return create(position_++);
}

}
