// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef DOGEN_RELATIONAL_ODB_TRACING_TRANSFORM_MODEL_SET_ODB_SQLITE_HXX
#define DOGEN_RELATIONAL_ODB_TRACING_TRANSFORM_MODEL_SET_ODB_SQLITE_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2046500 // 2.5.0-b.15
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <boost/shared_ptr.hpp>
#include <odb/boost/smart-ptr/pointer-traits.hxx>
#include <odb/boost/smart-ptr/wrapper-traits.hxx>
#include <odb/boost/optional/wrapper-traits.hxx>
#include <odb/boost/unordered/container-traits.hxx>
#include <odb/boost/date-time/sqlite/gregorian-traits.hxx>
#include <odb/boost/date-time/sqlite/posix-time-traits.hxx>
#include <odb/boost/multi-index/container-traits.hxx>
#include <odb/boost/uuid/sqlite/uuid-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20465UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "dogen.relational/types/tracing/transform_model_set.hpp"

#include "dogen.relational/odb/tracing/model_set_id-odb-sqlite.hxx"
#include "dogen.relational/odb/tracing/transform_id-odb-sqlite.hxx"

#include "dogen.relational/odb/tracing/transform_model_set-odb.hxx"

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // transform_model_set
  //
  template <typename A>
  struct query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >
  {
    // transform_id
    //
    struct transform_id_class_
    {
      transform_id_class_ ()
      {
      }

      // value
      //
      typedef
      sqlite::query_column<
        sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::query_type,
        sqlite::id_text >
      value_type_;

      static const value_type_ value;
    };

    static const transform_id_class_ transform_id;

    // model_set_id
    //
    struct model_set_id_class_
    {
      model_set_id_class_ ()
      {
      }

      // value
      //
      typedef
      sqlite::query_column<
        sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::query_type,
        sqlite::id_text >
      value_type_;

      static const value_type_ value;
    };

    static const model_set_id_class_ model_set_id;

    // type
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::dogen::relational::tracing::io_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    type_type_;

    static const type_type_ type;
  };

  template <typename A>
  const typename query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >::transform_id_class_::value_type_
  query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >::transform_id_class_::
  value (A::table_name, "\"TRANSFORM_ID\"", 0);

  template <typename A>
  const typename query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >::transform_id_class_
  query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >::transform_id;

  template <typename A>
  const typename query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >::model_set_id_class_::value_type_
  query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >::model_set_id_class_::
  value (A::table_name, "\"MODEL_SET_ID\"", 0);

  template <typename A>
  const typename query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >::model_set_id_class_
  query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >::model_set_id;

  template <typename A>
  const typename query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >::type_type_
  query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >::
  type (A::table_name, "\"TYPE\"", 0);

  template <typename A>
  struct pointer_query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >:
    query_columns< ::dogen::relational::tracing::transform_model_set, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::dogen::relational::tracing::transform_model_set, id_sqlite >:
    public access::object_traits< ::dogen::relational::tracing::transform_model_set >
  {
    public:
    struct image_type
    {
      // transform_id_
      //
      composite_value_traits< ::dogen::relational::tracing::transform_id, id_sqlite >::image_type transform_id_value;

      // model_set_id_
      //
      composite_value_traits< ::dogen::relational::tracing::model_set_id, id_sqlite >::image_type model_set_id_value;

      // type_
      //
      long long type_value;
      bool type_null;

      std::size_t version;
    };

    using object_traits<object_type>::id;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    typedef sqlite::no_id_object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 3UL;
    static const std::size_t id_column_count = 0UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
  };

  // transform_model_set
  //
}

#include "dogen.relational/odb/tracing/transform_model_set-odb-sqlite.ixx"

#include <odb/post.hxx>

#endif // DOGEN_RELATIONAL_ODB_TRACING_TRANSFORM_MODEL_SET_ODB_SQLITE_HXX
