/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * Copyright (C) 2012 Kitanda <info@kitanda.co.uk>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 */
#ifndef DOGEN_TACK_TYPES_ORIGIN_TYPES_HPP
#define DOGEN_TACK_TYPES_ORIGIN_TYPES_HPP

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
#pragma once
#endif

namespace dogen {
namespace tack {

/**
 * @brief What originated the model element.
 *
 * System models are models such as STL, boost, etc. They provide a way to
 * expose third party code into Dogen so that we can make use of these types.
 * They need to be hand-coded in for the moment.
 *
 * User models are regular Dogen models, normally made using Dia.
 */
enum class origin_types : unsigned int {
    invalid = 0, ///< Represents an uninitialised enum
    user = 1, ///< The model element was created by the user
    system = 2, ///< The model element was generated by the system
    unknown = 3 ///< The origin of the element is not yet known
};

} }

#endif
