/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * These files are code-generated via overrides to test dogen. Do not commit them.
 *
 * Generation timestamp: 2022-10-20T10:20:30
 * WARNING: do not edit this file manually.
 * Generated by MASD Dogen v1.0.33
 *
 * Copyright (C) 2012-2015 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 */
#include "dogen.text/test_data/entities/model_td.hpp"
#include "dogen.logical/test_data/entities/model_td.hpp"
#include "dogen.physical/test_data/entities/model_td.hpp"
#include "dogen.text/test_data/entities/logical_physical_region_td.hpp"
#include "dogen.identification/test_data/entities/logical_provenance_td.hpp"

namespace {

dogen::identification::entities::logical_provenance
create_dogen_identification_entities_logical_provenance(const unsigned int position) {
    return dogen::identification::entities::logical_provenance_generator::create(position);
}

dogen::logical::entities::model
create_dogen_logical_entities_model(const unsigned int position) {
    return dogen::logical::entities::model_generator::create(position);
}

dogen::physical::entities::model
create_dogen_physical_entities_model(const unsigned int position) {
    return dogen::physical::entities::model_generator::create(position);
}

dogen::text::entities::logical_physical_region
create_dogen_text_entities_logical_physical_region(const unsigned int position) {
    return dogen::text::entities::logical_physical_region_generator::create(position);
}

std::list<dogen::text::entities::logical_physical_region> create_std_list_dogen_text_entities_logical_physical_region(unsigned int position) {
    std::list<dogen::text::entities::logical_physical_region> r;
    for (unsigned int i(0); i < 4; ++i) {
        r.push_back(create_dogen_text_entities_logical_physical_region(position + i));
    }
    return r;
}

}

namespace dogen::text::entities {

model_generator::model_generator() : position_(0) { }

void model_generator::
populate(const unsigned int position, result_type& v) {
    v.provenance(create_dogen_identification_entities_logical_provenance(position + 0));
    v.logical(create_dogen_logical_entities_model(position + 1));
    v.physical(create_dogen_physical_entities_model(position + 2));
    v.logical_physical_regions(create_std_list_dogen_text_entities_logical_physical_region(position + 3));
}

model_generator::result_type
model_generator::create(const unsigned int position) {
    model r;
    model_generator::populate(position, r);
    return r;
}

model_generator::result_type*
model_generator::create_ptr(const unsigned int position) {
    model* p = new model();
    model_generator::populate(position, *p);
    return p;
}

model_generator::result_type
model_generator::operator()() {
    return create(position_++);
}

}
