#+title: Definition of Done
#+options: date:nil toc:nil author:nil num:nil

* About

This document defines what we consider to be the main milestone of
Dogen; the point at which we can consider it "done". It won't ever be
finished, of course, but we need to have a clear idea of when we
consider it to be "good enough" or else we'll be refactoring
forever. This will be release v1.0.

* What do we need to achieve

The following must be attained in order for it to be done:

- It must be possible to add a new file formatter by just adding a new
  header and implementation file.
- The meta-data refactoring must be complete, allowing users to supply
  licences, etc.
- All models must have doxygen documentation describing their
  purpose. The key types should be documented too.
- We must run sanity scripts on packages across all platforms to
  ensure we are providing good packages.
- Unstable packages (e.g latest) must be available for Download off of
  CI.
- Stable packages must be available in Debian via apt-get.
- We must support a language other than C++ to prove that the
  framework works with multiple languages.
- We must have a basic manual including examples all the main features
  of Dogen.

All of these tasks are already in the backlog.
