#+title: Release Notes for Sprint 48
#+options: date:nil toc:nil author:nil num:nil
#+todo: ANALYSIS IMPLEMENTATION TESTING | COMPLETED CANCELLED
#+tags: story(s) epic(e) task(t) note(n) spike(p)

* Release Notes

This file contains all stories that were closed during sprint 48.

The *Mission Statement* for this sprint is to try to get development
back up and running. We have stalled over the last few sprints.

** Development Stories Implemented

#+begin: clocktable :maxlevel 3 :scope subtree
Clock summary at [2014-04-28 Mon 21:04]

| Headline                                             | Time   |      |      |
|------------------------------------------------------+--------+------+------|
| *Total time*                                         | *6:37* |      |      |
|------------------------------------------------------+--------+------+------|
| Development Stories Implemented                      |        | 6:37 |      |
| IMPLEMENTATION Release notes and backlog grooming    |        |      | 0:18 |
| COMPLETED Log start and finish of dogen with version |        |      | 0:20 |
| COMPLETED Install packages into =/usr=               |        |      | 2:23 |
| COMPLETED Fix issues with database tests             |        |      | 2:54 |
| IMPLEMENTATION Rename =driver= to =knitter=          |        |      | 0:22 |
| IMPLEMENTATION Create a trivial Linux gcc script     |        |      | 0:20 |
#+end:

*** IMPLEMENTATION Release notes and backlog grooming                  :task:
    CLOCK: [2014-04-28 Mon 18:31]--[2014-04-28 Mon 18:37] =>  0:06
    CLOCK: [2014-04-28 Mon 08:28]--[2014-04-28 Mon 08:30] =>  0:02
    CLOCK: [2014-04-19 Sat 23:25]--[2014-04-19 Sat 23:35] =>  0:10

Updates to release notes and backlog.

*** Updates to the manual and readme files                             :task:

Use build downtime to update the manual and / or readme file.

*** COMPLETED Log start and finish of dogen with version              :story:
    CLOSED: [2014-04-28 Mon 16:33]
    CLOCK: [2014-04-28 Mon 18:21]--[2014-04-28 Mon 18:31] =>  0:10
    CLOCK: [2014-04-28 Mon 08:30]--[2014-04-28 Mon 08:40] =>  0:10

The log file of a non-verbose session of dogen provides no information
whatsoever about the version of dogen, git commit, etc.

: 2014-03-12 18:25:09.053599 [INFO] [engine.workflow] Workflow started.
: ...
: 2014-03-12 18:25:09.252724 [INFO] [engine.workflow] Workflow finished.

*** COMPLETED Install packages into =/usr=                            :story:
    CLOSED: [2014-04-27 Sun 15:29]
    CLOCK: [2014-04-27 Sun 13:06]--[2014-04-27 Sun 15:29] =>  2:23

As we will be using Docker to test the packages, we can now write
files into =/usr/bin= without fear. Move from =/opt= into =/usr=.

*** COMPLETED Remove versioning from packages                         :story:
    CLOSED: [2014-04-27 Sun 15:30]

We don't seem to have a particularly good story around versioning in
packages. It's best to remove it for now until we really understand
how it should work.

In addition, we will be using Docker to test the packages, making
versioning less of a necessity.

*** COMPLETED Fix issues with database tests                          :story:
    CLOSED: [2014-04-28 Mon 16:32]

Last sprint we solved the delays in nightlies by adding concurrency to
the tests; however, that broke the database tests. We need to refactor
the tests to allow them to run concurrently.

**** COMPLETED Setup erdos to run database tests                       :task:
     CLOSED: [2014-04-28 Mon 16:32]
     CLOCK: [2014-04-28 Mon 07:52]--[2014-04-28 Mon 08:28] =>  0:36
     CLOCK: [2014-04-22 Tue 07:53]--[2014-04-22 Tue 08:15] =>  0:22

Erdos is not using the PFH and as such cannot see the ODB install, so
the tests are not setup to run there. We need to create a local
directory with ODB (and EOS while we're at it), setup the =pgpass=
file and get the tests to run successfully.

**** COMPLETED Setup lorenz to run database tests                      :task:
     CLOSED: [2014-04-27 Sun 12:32]

After reinstall we lost the PFH so setup a minimal personal directory
with ODB and EOS.

**** COMPLETED Investigate errors in tests                             :task:
     CLOSED: [2014-04-27 Sun 12:31]
     CLOCK: [2014-04-27 Sun 10:35]--[2014-04-27 Sun 12:31] =>  1:56

We seem to have traffic-lighters in the database tests when executing
them concurrently. Somewhere they must be trampling on each others
feet.

*** IMPLEMENTATION Rename =driver= to =knitter=                       :story:
    CLOCK: [2014-04-28 Mon 18:38]--[2014-04-28 Mon 19:00] =>  0:22

As part of the naming epic "Naming of libraries and binaries", rename
driver. We should also get rid of the =dogen= shell script. Finally we
need to add some blurb to the manual to mention the whole "weaving"
theme.

*** IMPLEMENTATION Create a trivial Linux gcc script                  :story:
    CLOCK: [2014-04-22 Tue 08:15]--[2014-04-22 Tue 08:35] =>  0:20

The previous attempts to clean up the build environment were too
elaborate given the available time. We need to go back to basics with
a trivial script that works for Linux 32-bit and 64-bit with gcc.

*** Create a trivial Linux clang script                               :story:

We need to be able to build Linux clang 32-bit and 64-bit again.

** Deprecated Development Stories
