#+title: Sprint Backlog 47
#+options: date:nil toc:nil author:nil num:nil
#+todo: ANALYSIS IMPLEMENTATION TESTING | COMPLETED CANCELLED
#+tags: story(s) epic(e) task(t) note(n) spike(p)

* Stories

This file contains all stories that were closed during sprint 47.

The *Mission Statement* for this sprint is a continuation of the
previous sprint: to get the build environment back up and running
across all the build agents. By the end of this sprint we intend to
have all build agents with green builds, and the packages uploaded to
GDrive.

** Development Stories Implemented

#+begin: clocktable :maxlevel 3 :scope subtree
Clock summary at [2014-05-27 Tue 13:06]

| Headline                                         | Time   |      |      |
|--------------------------------------------------+--------+------+------|
| *Total time*                                     | *8:11* |      |      |
|--------------------------------------------------+--------+------+------|
| Development Stories Implemented                  |        | 8:11 |      |
| COMPLETED Sprint and product backlog grooming    |        |      | 1:08 |
| COMPLETED Updates to the manual and readme files |        |      | 5:51 |
| CANCELLED Complete the integral work for Linux   |        |      | 0:15 |
| COMPLETED Fix issues with missing builds         |        |      | 0:57 |
#+end:

*** COMPLETED Sprint and product backlog grooming                      :task:
    CLOSED: [2014-04-19 Sat 23:26]
    CLOCK: [2014-03-27 Thu 18:29]--[2014-03-27 Thu 18:47] =>  0:18
    CLOCK: [2014-03-27 Thu 07:52]--[2014-03-27 Thu 08:22] =>  0:30
    CLOCK: [2014-03-18 Tue 08:07]--[2014-03-18 Tue 08:12] =>  0:05
    CLOCK: [2014-03-18 Tue 07:52]--[2014-03-18 Tue 08:07] =>  0:15

Updates to sprint and product backlog.

*** COMPLETED Updates to the manual and readme files                   :task:
    CLOSED: [2014-04-19 Sat 23:26]
    CLOCK: [2014-03-25 Tue 07:51]--[2014-03-25 Tue 08:11] =>  0:20
    CLOCK: [2014-03-24 Mon 08:04]--[2014-03-24 Mon 08:50] =>  0:46
    CLOCK: [2014-03-21 Fri 07:56]--[2014-03-21 Fri 08:40] =>  0:44
    CLOCK: [2014-03-20 Thu 17:32]--[2014-03-20 Thu 18:02] =>  0:30
    CLOCK: [2014-03-20 Thu 07:56]--[2014-03-20 Thu 08:37] =>  0:41
    CLOCK: [2014-03-19 Wed 18:09]--[2014-03-19 Wed 18:50] =>  0:41
    CLOCK: [2014-03-19 Wed 07:58]--[2014-03-19 Wed 08:37] =>  0:39
    CLOCK: [2014-03-18 Tue 21:03]--[2014-03-18 Tue 21:45] =>  0:42
    CLOCK: [2014-03-18 Tue 18:24]--[2014-03-18 Tue 19:00] =>  0:36
    CLOCK: [2014-03-18 Tue 08:28]--[2014-03-18 Tue 08:40] =>  0:12

Use build downtime to update the manual and / or readme file.

*** CANCELLED Complete the integral work for Linux                    :story:
    CLOSED: [2014-04-19 Sat 23:26]
    CLOCK: [2014-03-18 Tue 08:12]--[2014-03-18 Tue 08:27] =>  0:15

Since we can't use docker, we need to figure out where we left
integral and get it in a state good enough to be used in production.

- it seems we have not pulled (or pushed) the latest integral work. We
  need to sync with lorenz before we proceed.

*** COMPLETED Fix issues with missing builds                          :spike:
    CLOSED: [2014-03-19 Wed 18:10]
    CLOCK: [2014-03-18 Tue 22:00]--[2014-03-18 Tue 22:57] =>  0:57

We seem to have no builds for the last few days, probably due to the
changes done while messing around with docker.

** Deprecated Development Stories
