#+title: Sprint Backlog 55
#+options: date:nil toc:nil author:nil num:nil
#+todo: ANALYSIS IMPLEMENTATION TESTING | COMPLETED CANCELLED POSTPONED
#+tags: { story(s) epic(e) task(t) note(n) spike(p) }
#+tags: { refactor(r) bug(b) feature(f) vision(v) }
#+tags: { meta_data(m) tests(a) packaging(q) media(h) build(u) validation(x) diagrams(w) frontend(c) backend(g) }
#+tags: dia(y) sml(l) cpp(k) config(o) formatters(d)

* Stories

This file contains all stories that were closed during sprint 55.

The *Mission Statement* for this sprint is to continue to finish
implementing the C++ model workflow skeleton, creating the end-to-end
pipeline for at least one formatter.

** Development Stories Implemented

#+begin: clocktable :maxlevel 3 :scope subtree
Clock summary at [2014-11-03 Mon 18:14]

| Headline                                           | Time   |      |      |
|----------------------------------------------------+--------+------+------|
| *Total time*                                       | *0:55* |      |      |
|----------------------------------------------------+--------+------+------|
| Development Stories Implemented                    |        | 0:55 |      |
| IMPLEMENTATION Sprint and product backlog grooming |        |      | 0:16 |
| IMPLEMENTATION Add support for facet settings      |        |      | 0:03 |
| COMPLETED Sort out postgres update problems        |        |      | 0:36 |
#+end:

*** IMPLEMENTATION Sprint and product backlog grooming                 :task:
    CLOCK: [2014-11-03 Mon 08:09]--[2014-11-03 Mon 08:16] =>  0:07
    CLOCK: [2014-11-03 Mon 07:59]--[2014-11-03 Mon 08:08] =>  0:09

Updates to sprint and product backlog.

*** IMPLEMENTATION Add support for facet settings                     :story:
    CLOCK: [2014-11-03 Mon 08:23]--[2014-11-03 Mon 08:26] =>  0:03

- create a "manager" or "initialiser" for each facet, responsible for
  registering all the formatters and the default settings.
- find all distinct facets supplied by formatters
- create a facet settings factory, given a facet
- apply factory to all facets in workflow
- supply all settings to formatter dispatcher, including map of facet
  settings by facet
- build the settings bundle in dispatcher

*** COMPLETED Sort out postgres update problems                       :spike:
    CLOSED: [2014-11-03 Mon 18:14]
    CLOCK: [2014-11-03 Mon 18:02]--[2014-11-03 Mon 18:14] =>  0:12
    CLOCK: [2014-11-03 Mon 08:26]--[2014-11-03 Mon 08:43] =>  0:17
    CLOCK: [2014-11-03 Mon 08:16]--[2014-11-03 Mon 08:23] =>  0:07

The latest dist-upgrade failed due to a format change on postgres
9.4. We need to drop and recreate the cluster or else we can't run
unit tests.

- dropped cluster 9.4 main
- created new cluster
- created user build with permissions to create dabatases
- altered it's password
- changed hba conf to use md5
- created databases from user build and added schemas
- un-commented create schema from database tests

*** Updates to the manual and readme files                       :task:media:

Use downtime to update the manual and / or readme file.

*** Refactor types header formatter            :task:refactor:formatters:cpp:

Make the main types header formatters look like the =om= types
formatter. This model was deleted around commit 10157ad.

This is still not quite right. We need to drive the formatting from
two things:

- user options
- available formatters

**** Tidy-up =types_main_header_file_formatter=                        :task:

Clean up internal functions in file and add documentation.

**** Make use of boilerplate                                           :task:

Generate the licence, etc using boilerplate formatter.

**** Copy across documentation from =om=                               :task:

We did a lot of doxygen comments that are readily applicable, copy
them across.

**** Make use of indenting stream                                      :task:

Remove uses of old indenter.

**** Copy across =om= types formatter tests                            :task:

Not sure how applicable this would be, but we may be able to scavenge
some tests.

*** Add include files at the formatter level    :task:refactor:meta_data:cpp:

We need to remove all the include files from =includer= which are
related to formatter specific code. We need to inject these
dependencies inside of the formatters.

- implement includer in terms of json files
- get includer to work off of object relationships
- remove relationships from transformer
- remove helper models boost and std

*** Includer generation should be done from meta-data         :task:refactor:

It would be nice if we could determine which includer files to create
by looking at the meta-data. For this we need a notion of an inclusion
group, defined at the model level:

- =cpp.types.includers.general=
- =cpp.types.includers.value_objects=
- ...

Under each of these one would configure the aspect:

- =cpp.types.includers.general.generate=: =true=
- =cpp.types.includers.general.file_name=: =a/b/c=
- =cpp.types.includers.general.is_system=: =false=

Then, each type, module etc would declare its membership (as a list):

- =cpp.includers.member=: =cpp.types.includers.general=
- =cpp.includers.member=: =cpp.types.includers.value_objects=
- ...

*Previous understanding*

We should simply go through all the types in the SML model and for
each type and each facet create the corresponding inclusion
path. locator can be used to generate standard paths, and a model
specific mapping is required for other models such as std.

Include then takes the relationships extracted by extractor, the
mappings generated by this mapper and simply appends to the inclusion
list the file names. it also appends the implementation specific
headers.

*** Support "cross-facet interference"                         :task:feature:

In a few cases its useful to disable bits of a facet when another
facet is switched off because those bits do not belong to the main
facet the formatter is working on. At present this happens in the
following cases:

- Forward declaration of serialisation in domain when serialisation is
  off
- Friend of serialisation in domain when serialisation is
  off
- declaration and implementation of to_stream when IO is off
- declaration and implementation of inserter when IO is off and
  integrated IO is on.

We need a way of accessing the on/off state of all facets from any
formatter so that they can make cross facet decisions. A quick hack
was to add yet another flag: =disable_io= which is disabled when the
IO facet is not present and passed on to the relevant formatters. This
needs to be replaced by a more general approach.

*** Add frontends and backends to =info= command line option  :story:feature:

#+begin_quote
*Story*: As a dogen user, I want to know what frontends and backends
are available in my dogen version so that I don't try to use features
that are not present.
#+end_quote

With the static registration of frontends and backends, we should add
some kind of mechanism to display whats on offer in the command line,
via the =--info= option. This is slightly tricky because the
=frontend= and =backend= models do not know of the command line. We
need a method in the frontends that returns a description and a method
in the workflow that returns all descriptions. These must be
static. The knitter can then call these methods and build the info
text.

*** Rename the include tags and add them to CPP model          :task:bug:sml:

Update all the JSON files with names in the form
=cpp.include.types.header_file=. Add properties in =cpp= to capture
these.

While we're at it, add support for =family= too.

** Deprecated Development Stories

Stories that do not make sense any longer.
