#+title: Sprint Backlog 79
#+options: date:nil toc:nil author:nil num:nil
#+todo: STARTED | COMPLETED CANCELLED POSTPONED
#+tags: { story(s) spike(p) }

* Mission Statement

- start implementing quilt.cpp formatters using yarn types;
- try to enable coverage support.

* Stories

** Active

#+begin: clocktable :maxlevel 3 :scope subtree :indent nil :emphasize nil :scope file :narrow 75 :formula %
#+CAPTION: Clock summary at [2016-02-01 Mon 20:51]
| <75>                                                                        |         |       |      |       |
| Headline                                                                    | Time    |       |      |     % |
|-----------------------------------------------------------------------------+---------+-------+------+-------|
| *Total time*                                                                | *33:59* |       |      | 100.0 |
|-----------------------------------------------------------------------------+---------+-------+------+-------|
| Stories                                                                     | 33:59   |       |      | 100.0 |
| Active                                                                      |         | 33:59 |      | 100.0 |
| COMPLETED Sprint and product backlog grooming                               |         |       | 4:10 |  12.3 |
| COMPLETED Merge all formatter assistants into one                           |         |       | 2:20 |   6.9 |
| COMPLETED Name builder should take only model name                          |         |       | 0:48 |   2.4 |
| COMPLETED Generate exceptions using yarn types                              |         |       | 2:21 |   6.9 |
| COMPLETED Generate modules using yarn types                                 |         |       | 0:32 |   1.6 |
| COMPLETED Delete all =quilt::cpp::formattable= types not in use             |         |       | 0:19 |   0.9 |
| COMPLETED Use dots to separate namespaces in binary names                   |         |       | 1:52 |   5.5 |
| COMPLETED Refactor resolver class                                           |         |       | 0:19 |   0.9 |
| COMPLETED Handle enumeration type dynamically                               |         |       | 1:05 |   3.2 |
| COMPLETED Generate enumerations using yarn types                            |         |       | 1:07 |   3.3 |
| COMPLETED Generate visitors using yarn types                                |         |       | 0:31 |   1.5 |
| COMPLETED Add initial support for MinGW and OSX                             |         |       | 2:28 |   7.3 |
| POSTPONED Create a debug build for clang in travis                          |         |       | 0:12 |   0.6 |
| COMPLETED How to attach helper methods to types dynamically                 |         |       | 1:16 |   3.7 |
| COMPLETED How to handle composition and pointers                            |         |       | 1:18 |   3.8 |
| COMPLETED Rename hash container to associative container                    |         |       | 0:42 |   2.1 |
| COMPLETED Clean up usage of is pointer in yarn                              |         |       | 2:03 |   6.0 |
| COMPLETED Rename aspect settings to element settings                        |         |       | 0:26 |   1.3 |
| COMPLETED Remove support for integrated io                                  |         |       | 0:37 |   1.8 |
| CANCELLED Implement io for inheritance in the io facet                      |         |       | 0:09 |   0.4 |
| COMPLETED Add a field for =quilt.cpp.helper_family=                         |         |       | 2:49 |   8.3 |
| CANCELLED Add formatter helpers to formatter properties                     |         |       | 3:20 |   9.8 |
| POSTPONED Add an helper method interface                                    |         |       | 3:15 |   9.6 |
#+TBLFM: $5='(org-clock-time% @3$2 $2..$4);%.1f
#+end:

*** COMPLETED Sprint and product backlog grooming                     :story:
    CLOSED: [2016-02-01 Mon 20:51]
    CLOCK: [2016-01-31 Sun 10:58]--[2016-01-31 Sun 11:05] =>  0:07
    CLOCK: [2016-01-31 Sun 10:45]--[2016-01-31 Sun 10:57] =>  0:12
    CLOCK: [2016-01-30 Sat 22:05]--[2016-01-30 Sat 22:16] =>  0:11
    CLOCK: [2016-01-28 Thu 21:30]--[2016-01-28 Thu 21:56] =>  0:26
    CLOCK: [2016-01-27 Wed 21:20]--[2016-01-27 Wed 21:37] =>  0:17
    CLOCK: [2016-01-24 Sun 23:19]--[2016-01-24 Sun 23:26] =>  0:07
    CLOCK: [2016-01-24 Sun 15:10]--[2016-01-24 Sun 15:28] =>  0:18
    CLOCK: [2016-01-23 Sat 20:40]--[2016-01-23 Sat 21:56] =>  1:16
    CLOCK: [2016-01-23 Sat 20:05]--[2016-01-23 Sat 20:22] =>  0:17
    CLOCK: [2016-01-22 Fri 13:11]--[2016-01-22 Fri 13:49] =>  0:38
    CLOCK: [2016-01-19 Tue 23:27]--[2016-01-19 Tue 23:30] =>  0:03
    CLOCK: [2016-01-18 Mon 21:55]--[2016-01-18 Mon 22:13] =>  0:18

Updates to sprint and product backlog.

*** COMPLETED Merge all formatter assistants into one                 :story:
    CLOSED: [2016-01-19 Tue 22:24]
    CLOCK: [2016-01-19 Tue 20:36]--[2016-01-19 Tue 22:24] =>  1:48
    CLOCK: [2016-01-18 Mon 23:09]--[2016-01-18 Mon 23:31] =>  0:22
    CLOCK: [2016-01-18 Mon 22:30]--[2016-01-18 Mon 22:40] =>  0:10

As part of the "yarnification" of the formatters, we need to be able
to use most of the entity formatter assistant properties over to the
base formatter assistant. We should get rid of the trivial formatting
assistant and entity formatting assistant and move all the code to the
base. The two methods that require an entity should receive it as an
input parameter.

*** COMPLETED Name builder should take only model name                :story:
    CLOSED: [2016-01-20 Wed 21:05]
    CLOCK: [2016-01-20 Wed 21:46]--[2016-01-20 Wed 22:04] =>  0:18
    CLOCK: [2016-01-20 Wed 20:35]--[2016-01-20 Wed 21:05] =>  0:30

At present name builder requires an entire model just to get the name
out of it.

*** COMPLETED Generate exceptions using yarn types                    :story:
    CLOSED: [2016-01-21 Thu 07:15]
    CLOCK: [2016-01-21 Thu 18:19]--[2016-01-21 Thu 18:26] =>  0:07
    CLOCK: [2016-01-21 Thu 18:10]--[2016-01-21 Thu 18:16] =>  0:06
    CLOCK: [2016-01-21 Thu 06:30]--[2016-01-21 Thu 07:15] =>  0:45
    CLOCK: [2016-01-20 Wed 22:05]--[2016-01-20 Wed 22:33] =>  0:28
    CLOCK: [2016-01-20 Wed 21:06]--[2016-01-20 Wed 21:45] =>  0:39
    CLOCK: [2016-01-19 Tue 23:11]--[2016-01-19 Tue 23:27] =>  0:16

Tasks completed:

- delete the quilt exception type;
- remove transformation support for exception;
- create a yarn element based assistant;
- update the formatter interfaces to use yarn types;
- update the yarn formatting workflow to process yarn exceptions;
- update the stitch templates to make use of yarn exceptions.
- cannot find formatter properties for
  quilt.cpp.types.exception_header_formatter

*** COMPLETED Generate modules using yarn types                       :story:
    CLOSED: [2016-01-21 Thu 18:51]
    CLOCK: [2016-01-21 Thu 18:52]--[2016-01-21 Thu 19:00] =>  0:08
    CLOCK: [2016-01-21 Thu 18:27]--[2016-01-21 Thu 18:51] =>  0:24

Tasks:

- delete the quilt formattable;
- remove transformation support;
- update the formatter interfaces to use yarn types;
- update the yarn formatting workflow to process yarn modules;
- update the stitch templates to make use of yarn modules.

*** COMPLETED Delete all =quilt::cpp::formattable= types not in use   :story:
    CLOSED: [2016-01-21 Thu 20:27]
    CLOCK: [2016-01-21 Thu 20:17]--[2016-01-21 Thu 20:27] =>  0:10
    CLOCK: [2016-01-21 Thu 19:01]--[2016-01-21 Thu 19:10] =>  0:09

We seem to have created a number of formattable types but not actually
used them in formatters. Remove them all.

*** COMPLETED Use dots to separate namespaces in binary names         :story:
    CLOSED: [2016-01-21 Thu 23:06]
    CLOCK: [2016-01-21 Thu 22:57]--[2016-01-21 Thu 23:16] =>  0:19
    CLOCK: [2016-01-21 Thu 21:23]--[2016-01-21 Thu 22:56] =>  1:33

Originally we started using underscores to separate namespaces in
binary names. However, since we added support for composite model
names, we also started using dots for this. We should use dots in
binary names as well, for consistency.

We should do the same for log file names too, e.g.:

: dogen_knitter_yarn.json.log

*** COMPLETED Improve resolution of partial types in resolver         :story:
    CLOSED: [2016-01-22 Fri 21:52]

*Rationale*: the current state of the code is more or less according
to this story.

At present the code in =resolve_partial_type= is one big hack. We
should create a "lookup" routine that given a qname, tries it on all
containers and returns true or false. Then we should have different
"attempt" routines that try modifying the qname according to a rule
and call the "lookup" routine to see if it worked or not. We should
then continue to the next rule until we exhaust all rules or we find a
match. Each rule should provide some logging.

*** COMPLETED Refactor resolver class                                 :story:
    CLOSED: [2016-01-22 Fri 21:54]
    CLOCK: [2016-01-22 Fri 21:35]--[2016-01-22 Fri 21:54] =>  0:19

We are supplying the model in the constructor and then modifying it
internally. We should use the same pattern as other yarn services and
supply the model on the main method.

*** COMPLETED Handle enumeration type dynamically                     :story:
    CLOSED: [2016-01-22 Fri 22:43]
    CLOCK: [2016-01-22 Fri 21:55]--[2016-01-22 Fri 22:42] =>  0:47
    CLOCK: [2016-01-22 Fri 21:16]--[2016-01-22 Fri 21:34] =>  0:18

Add some enumeration post-processing that assigns it a underlying
type. Should be done with merged model (look for a primitive type with
property =is_default_enumeration_type=).

This should be done as part of resolution perhaps; user provides a raw
type, we expand it during expansion and resolve it during
resolution. If the string is empty, we should use the default
enumeration type. It is chosen from the collection of
primitives. There can only be one type marked as
default. =is_enumeration_default_type=? Read from JSON file.

Merged stories:

*Set enumeration underlying type in yarn*

In cpp transformer we have hacked the underlying type of the
enumeration. Remove this hack and set it in SML. Still a hack, but
a tad better.

Actually this could be the first case where LAM/PIM is used: we could
call this something like integer.

This is also hacked in yarn_dia's transformer.

*** COMPLETED Generate enumerations using yarn types                  :story:
    CLOSED: [2016-01-22 Fri 23:48]
    CLOCK: [2016-01-22 Fri 22:54]--[2016-01-22 Fri 23:48] =>  0:54
    CLOCK: [2016-01-21 Thu 21:09]--[2016-01-21 Thu 21:22] =>  0:13

Tasks:

- handle enumeration type assignment within yarn (was done in quilt
  before).
- delete the quilt formattable;
- remove transformation support;
- update the formatter interfaces to use yarn types;
- update the yarn formatting workflow to process yarn enumerations;
- update the stitch templates to make use of yarn enumerations.

*** COMPLETED Generate visitors using yarn types                      :story:
    CLOSED: [2016-01-23 Sat 00:18]
    CLOCK: [2016-01-22 Fri 23:49]--[2016-01-23 Sat 00:20] =>  0:29

Tasks:

- delete the quilt formattable;
- remove transformation support;
- update the formatter interfaces to use yarn types;
- update the yarn formatting workflow to process yarn visitors;
- update the stitch templates to make use of yarn visitors.

*** COMPLETED Move code to C++ 14                                     :story:
    CLOSED: [2016-01-23 Sat 21:28]

*Rationale*: We are building in C++ 14.

#+begin_quote
*Story*: As a dogen user or developer, I want to make use of C++-14
features so that I can generate more modern code.
#+end_quote

Now that the standard is out, we should move to it. Both clang and gcc
have some kind of support at present, so it should be a matter of
compiling on this mode. However, as we have gcc 4.7 on OSX and
Windows, we would have to upgrade these compilers first.

We have already proven that the code builds out of the box in
sprint 50.

*** COMPLETED Add initial support for MinGW and OSX                   :story:
    CLOSED: [2016-01-24 Sun 00:29]
    CLOCK: [2016-01-23 Sat 23:25]--[2016-01-24 Sun 00:27] =>  0:56
    CLOCK: [2016-01-23 Sat 22:23]--[2016-01-23 Sat 23:25] =>  1:02
    CLOCK: [2016-01-23 Sat 22:14]--[2016-01-23 Sat 22:22] =>  0:08
    CLOCK: [2016-01-23 Sat 21:57]--[2016-01-23 Sat 22:13] =>  0:16

It seems its possible to build using MinGW on windows:

- [[http://help.appveyor.com/discussions/questions/372-build-setup-for-a-c-program][Build setup for a C program]]
- [[https://github.com/imazen/libpng/blob/master/appveyor.yml][libpng appveyor.yml]]
- [[https://github.com/jibsen/brieflz/blob/0c6fb73984f11e697dfaade5cdc5e291c1655c67/appveyor.yml][Removing Git's sh from the path]]. See also
- [[https://www.appveyor.com/updates/2015/05/30][Appveyor adds support for MinGW]]
- [[http://altrepo.eu/matyapiro31/mingw-w64-thrift/blob/master/appveyor.yml][mingw-w64-thrift]]

We should probably enable this on our AppVeyor build matrix.

We can also start adding support for OSX.

For now the objective of this story is just to explore these builds;
we will address errors later on.

*** COMPLETED Treat shared pointers as JSON objects                   :story:
    CLOSED: [2016-01-24 Sun 22:45]

*Rationale*: this has been implemented some time ago.

At present we are not treating shared pointers as objects:

:         s << "\"shared_ptr\": \"empty shared pointer\"";

We need to start outputting them as JSON objects, just like we do for
containers, with a name for the "pointee".

*** POSTPONED Create a debug build for clang in travis                :story:
    CLOSED: [2016-01-24 Sun 15:23]
    CLOCK: [2016-01-18 Mon 22:14]--[2016-01-18 Mon 22:26] =>  0:12

In order to enable code coverage we need to have a debug build. For
this we need to setup travis with a build matrix, with two build types
for clang (debug and release).

Example YML: [[https://github.com/Microsoft/GSL/blob/master/.travis.yml][GSL]]

We almost made this work, but now we have a problem: using BUILD_TYPE
seems to disable the stage folder in travis (though it works
locally). We probably shouldn't use the stage folder since its not a
CMake idiom.

*** COMPLETED How to attach helper methods to types dynamically       :story:
    CLOSED: [2016-01-24 Sun 16:39]
    CLOCK: [2016-01-24 Sun 16:40]--[2016-01-24 Sun 16:46] =>  0:06
    CLOCK: [2016-01-24 Sun 15:29]--[2016-01-24 Sun 16:39] =>  1:10

In order to cope with the removal of nested type info, we need a way
to determine what helper methods are required for a given yarn type.

For this we need a way to allow helper methods to bind dynamically to
types. This can be done by using meta-data. The helper method
registers a name and the type uses that name it its key for helper
method. Where possible the helper method should use the name of the
STL concept it is binding to. We need settings support for reading
this field, and registration support for helper methods (registrar,
etc).

We should also find a nicer way to package helper methods, maybe
aligned to a model and type or concept.

Once this is done we need to remove the =object_types= that exist in
yarn just to figure out what helper methods to use.

This must be implemented as follows:

- aspect settings need an additional optional property: formatter
  class. This is just a string. We read them in with the bundle. We
  need to associate this helper name with a non-qualified formatter
  name (e.g. =class_implementation_formatter=). Simple map of string
  to string (helper class to formatter "class"). This should be doable
  from the existing dynamic fields infrastructure, but we may not have
  the required expansion yet.
- formattables workflow need an additional repository: helpers. This
  contains the helpers by name, by formatter name. It is constructed
  by iterating through the model and asking each type for their aspect
  settings and collecting the helper classes per formatter.
- formatter properties needs to store the helpers for a given
  formatter, read out from the repository above.
- formatters need a helper interface and a helper registrar. Each
  helper template needs to call the registrar and register itself
  using the helper and formatter class.
- formatter helper needs to ask the registrar for all helpers given
  current formatter class (ownership hierarchy, formatter name) and
  helper class. If none are found it errors.
- once this infrastructure is in place, we need to remove nested type
  info and make sure everything still works.

Actually, we can get away with just a "type family" because the type
itself need not care about which formatters bind to which
helpers. This means we can simply say =cpp.type_family= is
=smart_pointer= and then ask for all helpers for this formatter class
(the helper must know its formatter class) which bind to this type
family. Resurrecting notes on type families:

- =cpp.type_family=: string, to convert to enum. e.g.:
  =smart_pointer=. note: do not convert to enum.
- =cpp.type.family=: we need a "choice" value type for this. note: use
  of dot instead of underscore is better.
- re-read prior (detailed) analysis in [[https://github.com/DomainDrivenConsulting/dogen/blob/master/doc/agile/sprint_backlog_67.org#implement-io-helper-method-generator][Implement io helper method
  generator]].

In this view, we then do:

- rename aspect settings to type settings since they are no longer at
  the aspect level.
- add family type to aspect settings.
- create a new settings class to contain all of the dependent type
  families. We need a good name for this.
- update formattables workflow to generate this new class and append
  it to bundle, adding repository etc as required.
- in formatters: create registrar, interface etc and update all helper
  methods to register themselves.
- make context more efficient by using references and create all
  contexts up front, supplying the formatting workflow with just a
  container of name to context. Context should also have a container
  of helper methods performatter, created by querying the registrar.
- assistant has a method to generate all helpers.

Note: when time comes to support includes in helper methods, we can
take a similar approach as we do for formatters now. The helper method
implements some kind of include provider interface, which is then used
by the inclusion dependencies builder. The only slight snag is that we
need to first resolve the type into a type family and then go to the
helper interface.

*** COMPLETED How to handle composition and pointers                  :story:
    CLOSED: [2016-01-24 Sun 23:26]
    CLOCK: [2016-01-24 Sun 23:08]--[2016-01-24 Sun 23:18] =>  0:10
    CLOCK: [2016-01-24 Sun 21:59]--[2016-01-24 Sun 23:07] =>  1:08

At present we manually detect composition via a bit of a hack (string
comparisons) and then use a helper to break the infinite cycle. When
we move to a world of dynamic helpers this is no longer possible.

In addition, we are also relying on knowing if an instance of a type
is a pointer or not. This works because we rely on knowing if our
containing type is a smart pointer or not.

This points to two more general problem: detecting cycles and
determining when to forward declare. Whenever there is a cycle we need
to forward declare. In addition, whenever we have a pointer we can
forward declare. Since we always use pointers for cycles, this means
detecting a pointer is sufficient. However, a pointer is a C/C++
concept so we need to map it to a language agnostic concept that
exists at the yarn level.

Another problem is that we capture hash container keys. This is
required so we can tell types to include hash. However we do this by
marking a type as =object_types::hash_container=. This can be renamed
to associative container to make it a bit more generic. We could have
a boolean =is_container= followed by an enumeration =container_type=:

- associative
- sequence
- ordered

We need to look at the STL concepts for these to make sure we are at
the right level. Ideally there should also be a concept for a smart
pointer as a container of one or zero. Couldn't find any. We need to
find a good name such as "resource manager", "resource holder"? This
would mean that "is pointer" then becomes something akin to "is
potentially weak relationship" - some kind of language agnostic
version of "can use forward declaration".

The final conclusion of all of this is that we need to refactor object
types slightly to make it language neutral and to remove hacks such as
service etc, but on the main we can't get away from it. Further, we
need "is pointer" to become "is weak", and for it to be populated in
three cases:

- if the owning class is also part of the nested type;
- if a resource holder is holding on to a type;
- if a type has a pointer or reference to a type (when we do support
  c++ syntax). The parser would be responsible for setting the
  property in the front end and we'd have to not set it in yarn if it
  has already been set. This can be ignored for now.

In C++ "is weak" means a forward declaration. For the first case we
also need an additional property at the nested type level: is self
referencing. If true, this means we found a cycle.

With this clean up we can also use object types to make some
validation on the nested type instantiations (e.g. resource holder
must have one and only one type parameter, etc). Add this to validator
story.

Merged stories:

*Move language-specific object types to meta-data*

There are a number of object types that exist solely to provide the
method helpers with information:

- smart_pointer
- hash_container
- sequence_container
- ordered_container

These should be conveyed using the meta-data.

*Test data generator does not detect cycles in object graph*

At present we handle composition correctly, but not other forms of
cycles in the object graph.

Let model M be composed of class A with a member of type class B, and
class B with a member of type =shared_ptr= to class A. The test data
generated for such model will contain an infinite loop. We need a way
to detect such loops, potentially in SML, and then generate code which
breaks the loop.

This could be done by explicitly checking if the type of any member
variable loops back into the type itself. Of course one could conceive
cycles that involve many edges in the object graph, and for these we'd
still generate invalid code.

Another approach would be to have an unordered map of type
association; the map would have the IDs of every type as we go further
into the association graph. It would be pushed and popped as we go in
and out of branches; at the same time we need to have a look back
capacity to see the few elements in the stack. When a pattern emerges
that involved types of a certain ID, they would stop creating any
further associations.

*** COMPLETED Rename hash container to associative container          :story:
    CLOSED: [2016-01-26 Tue 23:12]
    CLOCK: [2016-01-26 Tue 22:30]--[2016-01-26 Tue 23:12] =>  0:42

As part of the yarn tidy-up to avoid C++'isms, rename hash container
to associative container and all associated names such as hash
container keys, etc.

Remove ordered container as we seem to use it for sets and maps but
there is no difference in handling between these and the hash
versions.

*** COMPLETED Clean up usage of is pointer in yarn                    :story:
    CLOSED: [2016-01-27 Wed 22:12]
    CLOCK: [2016-01-27 Wed 21:39]--[2016-01-27 Wed 22:13] =>  0:34
    CLOCK: [2016-01-26 Tue 23:13]--[2016-01-26 Tue 23:27] =>  0:14
    CLOCK: [2016-01-26 Tue 20:45]--[2016-01-26 Tue 22:00] =>  1:15

We need to make our usage of is pointer more language neutral. In
reality what we really mean is "can I use an incomplete class
declaration for this type?". See [[http://www-01.ibm.com/support/knowledgecenter/SSPSQF_9.0.0/com.ibm.xlcpp111.aix.doc/language_ref/cplr060.html][Incomplete class declarations]]. We
need to leave object types as is (e.g. with =smart_pointer=) because
we won't be changing nested type info just now, but we should at least
tidy up yarn properly.

There are three moving parts to this task:

- the association types in =Associatable=: we must not use the word
  "weak" to avoid confusion with UML terminology. We can use one of
  the following: opaque, incomplete, partial. In addition, "regular"
  is also a bad word. The opposites would then be: transparent,
  complete, full.
- the type instantiation in =nested_name=: are children opaque?
- the type itself: provides opaqueness? is opaqueness provider?

Tasks:

- create a property at object level: allows_incomplete

*Previous Understanding*

Tasks:

- rename hash container to associative container and all associated
  names such as hash container keys, etc.
- rename smart pointer to resource holder.
- investigate the usage of ordered container, and if not used, remove
  it.

We need to update all JSON documents, parser etc. Do not address the
"user defined" entries at this point.

Merged stories:

*Improve handling of weak relationships in nested name*

Tasks:

- rename is pointer to is weak;
- add a is self referencing property which is true if the nested name
  refers to the owning object.
- propagate these changes to nested type info and remove the composite
  vs domain type distinction in test data.

*** COMPLETED Rename aspect settings to element settings              :story:
    CLOSED: [2016-01-27 Wed 22:28]
    CLOCK: [2016-01-27 Wed 22:14]--[2016-01-27 Wed 22:28] =>  0:14
    CLOCK: [2016-01-24 Sun 21:46]--[2016-01-24 Sun 21:58] =>  0:12

These will no longer be confined to aspects so need to be
renamed. Actually =element= makes more sense than =type=, so it maps
back to =yarn::element= (at least conceptually).

*** COMPLETED Remove support for integrated io                        :story:
    CLOSED: [2016-01-27 Wed 23:22]
    CLOCK: [2016-01-27 Wed 22:44]--[2016-01-27 Wed 23:21] =>  0:37

We've been carrying this feature since the early days of dogen but we
don't really have a good use case for it now and it does add a lot of
complexity - its the only case where a feature can either be part of a
facet (types) or exist as its own facet (io). Remove it, and leave
just the io facet.

*** CANCELLED Implement io for inheritance in the io facet            :story:
    CLOSED: [2016-01-27 Wed 23:31]
    CLOCK: [2016-01-27 Wed 23:22]--[2016-01-27 Wed 23:31] =>  0:09

*Rationale*: this cannot be done; it is a limitation of how resolution
works in the presence of inheritance. See [[http://stackoverflow.com/questions/4164902/overloading-and-in-inherited-classes][Overloading << and >> in
inherited classes]].

At present we use the types facet to implement io when in
inheritance. This causes unnecessary complexity in the formatter
helpers. We need to try to implement it purely in the io facet.

*** COMPLETED Add a field for =quilt.cpp.helper_family=               :story:
    CLOSED: [2016-01-31 Sun 10:55]
    CLOCK: [2016-01-30 Sat 21:16]--[2016-01-30 Sat 22:04] =>  0:48
    CLOCK: [2016-01-29 Fri 21:45]--[2016-01-29 Fri 22:51] =>  1:06
    CLOCK: [2016-01-28 Thu 07:02]--[2016-01-28 Thu 07:12] =>  0:10
    CLOCK: [2016-01-28 Thu 06:56]--[2016-01-28 Thu 07:01] =>  0:05
    CLOCK: [2016-01-28 Thu 06:29]--[2016-01-28 Thu 06:55] =>  0:26
    CLOCK: [2016-01-27 Wed 22:29]--[2016-01-27 Wed 22:43] =>  0:14

We need to:

- determine all of the required values given the existing helper
  methods.
- add the field and update all data files. Actually, instead of
  =family= we should call it =helper_family= to make it clear.
- add a =helper_family= property in =element= settings and the
  machinery to read the data files.

One interesting point: the helper methods represent either a concept
(i.e. smart pointer) or a concrete type (i.e. boost date time).

To avoid confusion we should probably use concept-like naming
(e.g. =SmartPointer=).

Names:

- AssociativeContainer
- SequenceContainer
- BoostDate
- Dereferenceable: merged Optional, SmartPointer
- Pair
- BoostPath
- BoostPtime
- BoostPtree
- BoostTimeDuration
- BoostVariant
- String
- Boolean
- Character
- Number

To implement element settings retrieval:

- rename root_object_field_values to just field_values and all
  related functions: actually these are really root object specific so
  do not rename.
- add field definition and value.
- update make method to read in value.
- problem: in the past we only created setting bundles for generatable
  types. However, we now need to do this for all types in order to
  access this property. This will have an impact on performance. The
  solution to this problem is to take a similar approach to what we
  did for includes: create settings machinery to read out this one
  property, create a repository of this property by name, and then use
  these to construct the formatter properties with all of the
  dependent helper methods.
- note we are calling the field "helper family" not "formatter helper
  family" because it is scoped in =quilt.cpp=, and the whole point of
  =quilt.cpp= is to provide formatters.

Fixes:

- rename element settings back to aspect settings.
- create a settings class just for helper settings and associated
  classes. Add helper family to this class.

*** CANCELLED Add formatter helpers to formatter properties           :story:
    CLOSED: [2016-01-31 Sun 22:32]
    CLOCK: [2016-01-31 Sun 12:26]--[2016-01-31 Sun 12:37] =>  0:11
    CLOCK: [2016-01-31 Sun 11:45]--[2016-01-31 Sun 12:25] =>  0:40
    CLOCK: [2016-01-31 Sun 11:12]--[2016-01-31 Sun 11:44] =>  0:32
    CLOCK: [2016-01-31 Sun 11:06]--[2016-01-31 Sun 11:11] =>  0:05
    CLOCK: [2016-01-31 Sun 09:41]--[2016-01-31 Sun 10:44] =>  1:03
    CLOCK: [2016-01-31 Sun 09:20]--[2016-01-31 Sun 09:40] =>  0:20
    CLOCK: [2016-01-31 Sun 08:50]--[2016-01-31 Sun 09:19] =>  0:29

We need a place to store all of the formatter helper families a given
type is associated with.

Notes:

- create a helper properties repository in formattables that stores
  the helper properties for each type in model. We just need a map of
  string to string. Add all associated machinery (workflow, etc).
- follow the same pattern as in inclusion directives / inclusion
  dependencies. So the name is helper family / helper family
  dependencies. Not the best name but it will do for now. We just need
  a helper family dependencies repository that has a map of string to
  list of string.
- add formatter helper family dependencies to formatter
  properties as a list of string. Add processing to populate this.
- actually we need to expand the helper family into a formatter
  specific dependency or else it would make little sense to add this
  to the formatter properties - e.g. these are type level dependencies,
  rather than formatter dependencies so we'd just be duplicating the
  same list for every formatter and then later on have to figure out
  which dependencies apply to what formatters.

*** POSTPONED Add an helper method interface                          :story:
    CLOSED: [2016-02-01 Mon 20:51]
    CLOCK: [2016-01-31 Sun 22:30]--[2016-01-31 Sun 22:41] =>  0:11
    CLOCK: [2016-01-31 Sun 22:12]--[2016-01-31 Sun 22:29] =>  0:17
    CLOCK: [2016-01-31 Sun 16:57]--[2016-01-31 Sun 17:07] =>  0:10
    CLOCK: [2016-01-31 Sun 16:32]--[2016-01-31 Sun 16:56] =>  0:24
    CLOCK: [2016-01-31 Sun 16:18]--[2016-01-31 Sun 16:31] =>  0:13
    CLOCK: [2016-01-31 Sun 15:39]--[2016-01-31 Sun 16:17] =>  0:38
    CLOCK: [2016-01-31 Sun 14:34]--[2016-01-31 Sun 15:38] =>  1:04
    CLOCK: [2016-01-31 Sun 13:42]--[2016-01-31 Sun 14:00] =>  0:18

We should also investigate on the need for the nested type info
assistant.

Tasks:

- create interface.
- create a registrar for interface with family and formatter name.
- update all helpers to implement interface and to register
  themselves.
- it seems we have two use cases here: the formatter helper interface
  for formatting purposes and the helper family interface that tells
  us what formatter this helper belongs to. We do not want to leak
  details of formatting into formattables. We need to find a name for
  such an interface in formattables, a bit like the inclusion
  dependencies provider. Formatter helper details provider? We can
  then extend the existing formattables registrar and container to
  store this interface; the formatter helper interface can extend this
  interface; the main workflow returns all registered formatter
  helpers in terms of the formatter helper details provider interface.
- problem: we need additional properties related to the helper which
  have been hard-coded:
  - requires generic string; in a general form "string conversion
    method";
  - requires quoting;
  - requires tidying up; in a general form "remove unprintable
    characters";
  - requires hashing helper method; in a general form: we need a way
    to query the helper settings to figure out if a given type has an
    associated helper method for a given formatter, and if we need to
    call it implicitly or explicitly; and, if explicitly, we need to
    ask the helper method formatter for the name of the helper method.
  - requires dereferencing; for pointer types.
- seems like yet again we found the wrong solution for this
  problem. We need to create a top-level set of helper settings for
  each type with all additional properties; propagate those into
  formatters via context; and then use the assistant to loop through
  the nested name (nested info for now) and pick the helper
  settings. It should also consult the registrar to see if there are
  any helpers available for this formatter and family.

** Deprecated
*** CANCELLED Consider renaming nested name                           :story:
    CLOSED: [2016-01-07 Thu 20:18]

*Rationale*: the final conclusion on this was that nested name is the
best of a bad bunch. See Sprint 77 stories on renames for details.

*New understanding*:

This story requires further analysis. Blindly following the composite
pattern was tried but it resulted in a lot of inconsistencies because
we then had to follow MEC-33 and create =abstract_qname=; however, the
nested qname does not really behave like a composite qname; its more
like the difference between a type in isolation and a type
instantiated as an argument of a function. For example, whilst the
type in isolation may have unknown template parameters, presumably, as
an argument of a function these have been instantiated with real
types.

One way to solve this is just to make the type name a bit more
explicit rather than try to imply the composite pattern
(e.g. "nested"). We need a name that signifies "instantiated
type". Look at the C++ standard for the difference between defining a
generic type and instantiating a generic type.

No good names yet (type reference, type instantiation, instantiated
name). What are we trying to represent: an identifier which points to
a complete definition of a name such that the name can be instantiated
as a type in the underlying language. By "instantiated" we mean used
to define variables of this type. In this light: instantiable name,
definable name? If we choose instantiable name, we could then rename
"children" to type arguments.

Other notes:

- there is such a thing as a element instance identifier. We call it
  nested name at present. The element instance identifier identifies
  instantiations of types. It models two cases: for the case where the
  type has no type parameters, the instance identifier is equal to the
  element identifier; for all other cases, it is a hierarchical
  collection of element identifiers, modeling the type parameter
  structure.

*Previous understanding*:

We should just follow the composite pattern in the naming.
*** CANCELLED ODB options file is generated even when disabled        :story:
    CLOSED: [2016-01-20 Wed 20:39]

*Rationale*: this was due to incorrect key name for
=yarn.dia.comment=. We already have a story for better validation.

At present it seems the file is always generated regardless of the
meta-data. This is probably due to a typo in the field name.

*** CANCELLED Access model name from within formatters workflow       :story:
    CLOSED: [2016-01-24 Sun 15:25]

*Rationale*: We removed the need for the model name when building
names.

In order for the assistant to build names, it will need to be able to
access the yarn model name.
