#+title: Sprint Backlog 56
#+options: date:nil toc:nil author:nil num:nil
#+todo: ANALYSIS IMPLEMENTATION TESTING | COMPLETED CANCELLED POSTPONED
#+tags: { story(s) epic(e) task(t) note(n) spike(p) }
#+tags: { refactor(r) bug(b) feature(f) vision(v) }
#+tags: { meta_data(m) tests(a) packaging(q) media(h) build(u) validation(x) diagrams(w) frontend(c) backend(g) }
#+tags: dia(y) sml(l) cpp(k) config(o) formatters(d)

* Stories

This file contains all stories that were closed during sprint 56.

The *Mission Statement* for this sprint is to finish implementing the
C++ model workflow skeleton, moving across all of the formatting code
for the class formatter.

** Development Stories Implemented

#+begin: clocktable :maxlevel 3 :scope subtree
Clock summary at [2014-11-20 Thu 08:09]

| Headline                                                       | Time   |      |      |
|----------------------------------------------------------------+--------+------+------|
| *Total time*                                                   | *2:08* |      |      |
|----------------------------------------------------------------+--------+------+------|
| Development Stories Implemented                                |        | 2:08 |      |
| IMPLEMENTATION Sprint and product backlog grooming             |        |      | 0:13 |
| COMPLETED Implement path spec details builder for class header |        |      | 1:55 |
#+end:

*** IMPLEMENTATION Sprint and product backlog grooming                 :task:
    CLOCK: [2014-11-20 Thu 08:04]--[2014-11-20 Thu 08:09] =>  0:05
    CLOCK: [2014-11-17 Mon 07:45]--[2014-11-17 Mon 07:53] =>  0:08

Updates to sprint and product backlog.

*** Updates to the manual and readme files                       :task:media:

Use downtime to update the manual and / or readme file.

*** COMPLETED Implement path spec details builder for class header     :task:
    CLOSED: [2014-11-20 Thu 08:04]
    CLOCK: [2014-11-20 Thu 07:53]--[2014-11-20 Thu 08:04] =>  0:11
    CLOCK: [2014-11-19 Wed 19:39]--[2014-11-19 Wed 19:49] =>  0:10
    CLOCK: [2014-11-19 Wed 17:54]--[2014-11-19 Wed 18:21] =>  0:27
    CLOCK: [2014-11-17 Mon 17:54]--[2014-11-17 Mon 18:41] =>  0:47
    CLOCK: [2014-11-17 Mon 07:53]--[2014-11-17 Mon 08:13] =>  0:20

We need to implement the interface for path spec details builder.

*** Create a compact form of qname io                                 :story:

#+begin_quote
*Story*: As a dogen developer and user, I want to quickly identify an
instance of an SML type that is causing problems.
#+end_quote

At present we are using the JSON-based qname IO to dump qnames to the
log. For exceptions we use the simple name. There are downsides to
both of these approaches. With JSON we have a lot of moving parts that
obscure the vital information. With the simple name we miss all the
context for the type.

What we really need is a second type of IO for qnames that is
compacted to the absolute minimum. For example we could use dots to
concatenate all of the qname properties: =a.b.c=.

This will make the log files a lot smaller as well. Before:

: 2014-11-06 19:50:35.253844 [DEBUG] [sml.json_hydrator] Type has no containing module:  { "__type__": "dogen::sml::qname", "model_name": "", "external_module_path": [ ] , "module_path": [ ] , "simple_name": "long double" }

After:

: 2014-11-06 19:50:35.253844 [DEBUG] [sml.json_hydrator] Type has no containing module:  "long double"

We should add an SML utility function that does this work. We should
then do a grep for all instances of qname IO includes and for each,
replace it with the new utility function.

Finally we should raise a vision jira to make this either an extension
method (if these are supported in C++-17) or a manually generated
method on qname when we have a merging code generator.

*** Make use of path spec details in formatter                         :task:

Now that we have finished generating the path spec details, we should
use them in the class formatter. This may also require some tidy-up in
the path spec details generation.

*** Create a transformation and formatting sub-workflow       :task:refactor:

At present we have two template functions in the main workflow,
linking the different steps of transformation and formatting. However,
it may make more sense to plug in to the all types traversal. For this
we need a sub-workflow that owns the model and the transformer and
which overloads =operator()=. It produces files.

It can receive a formatter dispatcher and a transformer on
construction and keep references these. Execute returns the list of
files.

*** Tidy-up sml consumer interface                            :task:refactor:

After implementing the includes for the class header formatter we
should figure out if we need the multiple passes machinery. Most
likely all of that should be scraped.

*** Implement class header formatter           :task:refactor:formatters:cpp:

- look at the old =om= types formatter implementation to see if there
  is any code to scavenge. This model was deleted around commit
  10157ad.

**** Tidy-up =types_main_header_file_formatter=                        :task:

Clean up internal functions in file and add documentation.

**** Copy across documentation from =om=                               :task:

We did a lot of doxygen comments that are readily applicable, copy
them across.

**** Make use of indenting stream                                      :task:

Remove uses of old indenter.

**** Copy across =om= types formatter tests                            :task:

Not sure how applicable this would be, but we may be able to scavenge
some tests.

** Deprecated Development Stories

Stories that do not make sense any longer.
