name: Nightly Create Branch

on:
   schedule:
     - cron: '0 0 * * *'

jobs:
  build:
    name: ${{matrix.family}}-${{matrix.compiler}}-${{matrix.buildtype}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        name: [linux-gcc]
        buildtype: [release]
        include:
          - name: linux-gcc
            family: linux
            os: ubuntu
            compiler: gcc
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: ${{matrix.family}}-${{matrix.compiler}}-${{matrix.buildtype}}
          max-size: 1000M

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          appendedCacheKey: ${{matrix.name}}${{matrix.buildtype}}

      - name: Setup test data
        run: ./build/scripts/github.setup.${{matrix.family}}.sh

      - name: Run CTest workflow
        env:
          WITH_FULL_GENERATION: ON
          preset: ${{matrix.family}}-${{matrix.compiler}}-${{matrix.buildtype}}
        run: |
          export DOGEN_BUILD_PROVIDER="github"
          export DOGEN_BUILD_COMMIT="${GITHUB_SHA}"
          export DOGEN_BUILD_NUMBER="${GITHUB_RUN_NUMBER}"
          export DOGEN_BUILD_TIMESTAMP=`date "+%Y/%m/%d %H:%M:%S"`
          export DOGEN_BUILD_DATE=`date "+%Y%m%d"`
          export cmake_args="build_group=Nightly,build_name=${preset},with_full_generation=ON"
          cmake_args="${cmake_args},code_coverage=1"
          ctest -VV --timeout 12000 --preset ${preset} --script "CTest.cmake,${cmake_args}"
          git config user.name 'GitHub Actions'
          git config user.email noreply@github.com
          git branch -d nightly || true
          git push origin --delete nightly || true
          git checkout -b nightly
          git add -A 1>/dev/null
          git commit -m 'Generated code.' 1>/dev/null
          git push origin nightly

      - name: Gitter
        uses: juztcode/gitter-github-action@v2
        with:
          room-id: ${{secrets.GITTER_ROOM_ID}}
          token: ${{secrets.GITTER_TOKEN}}
          text: ${{github.workflow}} - ${{job.status}}
