name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unix:
    name: ${{matrix.os}}-${{matrix.cxx}}-${{matrix.buildtype}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        name: [ubuntu-gcc, ubuntu-clang, macos-clang]
        buildtype: [Debug, Release]
        include:
          - name: ubuntu-gcc
            os: ubuntu
            cxx: g++
            cc: gcc
            triplet: x64-linux
          - name: ubuntu-clang
            os: ubuntu
            cxx: clang++
            cc: clang
            triplet: x64-linux
          - name: macos-clang
            os: macos
            cxx: clang++
            cc: clang
            triplet: x64-osx
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Set Environment vars
        run: |
          echo "CXX=${{matrix.cxx}}" >> $GITHUB_ENV
          echo "CC=${{matrix.cc}}" >> $GITHUB_ENV

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgTriplet: ${{matrix.triplet}}
          appendedCacheKey: ${{matrix.name}}${{matrix.buildtype}}
          vcpkgGitCommitId: 5568f110b509a9fd90711978a7cb76bae75bb092

      - name: Build with CMake
        uses: lukka/get-cmake@latest

  windows:
    name: ${{matrix.os}}-${{matrix.cxx}}-${{matrix.buildtype}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        name: [windows-msvc]
        buildtype: [Debug, Release]
        include:
          - name: windows-msvc
            os: windows
            cxx: cl.exe
            cc: cl.exe
            triplet: x64-windows

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Set Environment vars
        run: |
          echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgTriplet: ${{matrix.triplet}}
          appendedCacheKey: ${{matrix.name}}${{matrix.buildtype}}
          vcpkgGitCommitId: 5568f110b509a9fd90711978a7cb76bae75bb092

      - name: Build with CMake
        uses: lukka/get-cmake@latest
