/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * These files are code-generated via overrides to test dogen. Do not commit them.
 *
 * Generation timestamp: 2022-10-20T10:20:30
 * WARNING: do not edit this file manually.
 * Generated by MASD Dogen v1.0.33
 *
 * Copyright (C) 2012-2015 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 */
#include <sstream>
#include "dogen.physical/test_data/entities/path_properties_td.hpp"
#include "dogen.physical/test_data/entities/inclusion_directives_td.hpp"

namespace {

boost::filesystem::path
create_boost_filesystem_path(const unsigned int position) {
    std::ostringstream s;
    s << "/a/path/number_" << position;
    return boost::filesystem::path(s.str());
}

std::string create_std_string(const unsigned int position) {
    std::ostringstream s;
    s << "a_string_" << position;
    return s.str();
}

dogen::physical::entities::inclusion_directives
create_dogen_physical_entities_inclusion_directives(const unsigned int position) {
    return dogen::physical::entities::inclusion_directives_generator::create(position);
}

std::list<std::string> create_std_list_std_string(unsigned int position) {
    std::list<std::string> r;
    for (unsigned int i(0); i < 4; ++i) {
        r.push_back(create_std_string(position + i));
    }
    return r;
}

}

namespace dogen::physical::entities {

path_properties_generator::path_properties_generator() : position_(0) { }

void path_properties_generator::
populate(const unsigned int position, result_type& v) {
    v.file_path(create_boost_filesystem_path(position + 0));
    v.header_guard(create_std_string(position + 1));
    v.inclusion_path(create_boost_filesystem_path(position + 2));
    v.inclusion_directives(create_dogen_physical_entities_inclusion_directives(position + 3));
    v.inclusion_dependencies(create_std_list_std_string(position + 4));
    v.using_dependencies(create_std_list_std_string(position + 5));
    v.relative_path(create_boost_filesystem_path(position + 6));
}

path_properties_generator::result_type
path_properties_generator::create(const unsigned int position) {
    path_properties r;
    path_properties_generator::populate(position, r);
    return r;
}

path_properties_generator::result_type*
path_properties_generator::create_ptr(const unsigned int position) {
    path_properties* p = new path_properties();
    path_properties_generator::populate(position, *p);
    return p;
}

path_properties_generator::result_type
path_properties_generator::operator()() {
    return create(position_++);
}

}
