/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * These files are code-generated via overrides to test dogen. Do not commit them.
 *
 * Generation timestamp: 2022-10-20T10:20:30
 * WARNING: do not edit this file manually.
 * Generated by MASD Dogen v1.0.33
 *
 * Copyright (C) 2012-2015 Marco Craveiro <marco.craveiro@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 */
#include "dogen.physical/test_data/entities/relations_td.hpp"
#include "dogen.physical/test_data/entities/relation_status_td.hpp"
#include "dogen.physical/test_data/entities/constant_relation_td.hpp"
#include "dogen.physical/test_data/entities/variable_relation_td.hpp"
#include "dogen.physical/test_data/entities/hard_coded_relation_td.hpp"

namespace {

dogen::physical::entities::relation_status
create_dogen_physical_entities_relation_status(const unsigned int position) {
    return dogen::physical::entities::relation_status_generator::create(position);
}

dogen::physical::entities::constant_relation
create_dogen_physical_entities_constant_relation(const unsigned int position) {
    return dogen::physical::entities::constant_relation_generator::create(position);
}

std::list<dogen::physical::entities::constant_relation> create_std_list_dogen_physical_entities_constant_relation(unsigned int position) {
    std::list<dogen::physical::entities::constant_relation> r;
    for (unsigned int i(0); i < 4; ++i) {
        r.push_back(create_dogen_physical_entities_constant_relation(position + i));
    }
    return r;
}

dogen::physical::entities::variable_relation
create_dogen_physical_entities_variable_relation(const unsigned int position) {
    return dogen::physical::entities::variable_relation_generator::create(position);
}

std::list<dogen::physical::entities::variable_relation> create_std_list_dogen_physical_entities_variable_relation(unsigned int position) {
    std::list<dogen::physical::entities::variable_relation> r;
    for (unsigned int i(0); i < 4; ++i) {
        r.push_back(create_dogen_physical_entities_variable_relation(position + i));
    }
    return r;
}

dogen::physical::entities::hard_coded_relation
create_dogen_physical_entities_hard_coded_relation(const unsigned int position) {
    return dogen::physical::entities::hard_coded_relation_generator::create(position);
}

std::list<dogen::physical::entities::hard_coded_relation> create_std_list_dogen_physical_entities_hard_coded_relation(unsigned int position) {
    std::list<dogen::physical::entities::hard_coded_relation> r;
    for (unsigned int i(0); i < 4; ++i) {
        r.push_back(create_dogen_physical_entities_hard_coded_relation(position + i));
    }
    return r;
}

}

namespace dogen::physical::entities {

relations_generator::relations_generator() : position_(0) { }

void relations_generator::
populate(const unsigned int position, result_type& v) {
    v.status(create_dogen_physical_entities_relation_status(position + 0));
    v.constant(create_std_list_dogen_physical_entities_constant_relation(position + 1));
    v.variable(create_std_list_dogen_physical_entities_variable_relation(position + 2));
    v.hard_coded(create_std_list_dogen_physical_entities_hard_coded_relation(position + 3));
}

relations_generator::result_type
relations_generator::create(const unsigned int position) {
    relations r;
    relations_generator::populate(position, r);
    return r;
}

relations_generator::result_type*
relations_generator::create_ptr(const unsigned int position) {
    relations* p = new relations();
    relations_generator::populate(position, *p);
    return p;
}

relations_generator::result_type
relations_generator::operator()() {
    return create(position_++);
}

}
